Implementation Plan. Part 1 - for the universe
1. things to crawl to filter or create a portfolio universe
   - 시가총액(Market Capitalization a.k.a "market cap")
   - "BV" (Book Value, Asset - Liability = SH's Equity)
   - PBR(Price-to-Book Ratio, 주가순자산비율)
   - 상장주식수

In [1]:
#Import packages
import requests 
from bs4 import BeautifulSoup

import numpy as np
import pandas as pd

In [2]:
# Crawler Building
# setting URL

url = "http://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn%3Fsosok%3D{0}%26page%3D{1}&fieldIds={2}&fieldIds={3}&fieldIds={4}&fieldIds={5}&fieldIds={6}&fieldIds={7}".format('0',
                                                                                                                                                                                                                                                             '1', 
                                                                                                                                                                                                                                                             'quant',
                                                                                                                                                                                                                                                             'listed_stock_cnt',
                                                                                                                                                                                                                                                             'market_sum',
                                                                                                                                                                                                                                                             'property_total',
                                                                                                                                                                                                                                                             'debt_total',
                                                                                                                                                                                                                                                             'pbr')
"""options to choose 
   1. 거래량 : 'quant'
   2. 시가 : 'open_val'
   3. 고가 : 'high_val'
   4. 저가 : 'loq_val' 
   5. 매수호가 : 'ask_buy'
   6. 매도호가 : 'ask_sell' 
   7. 매수총잔량 : 'buy_total'
   8. 매도총잔량 : 'sell_total'
   9. 거래대금(백만) : 'amount' 
   10. 전일거래량 : 'prev_quant'
   11. 외국인비율 : 'frgn_rate'
   12. 상장주식수(천주) : 'listed_stock_cnt'
   13. 시가총액(억) : 'market_sum'
   14. 자산총계(억) : 'property_total'
   15. 부채총계(억) : 'debt_total' 
   16. 매출액(억) : 'sales'
   17. 매출액증가율 : 'sales_increasing_rate'
   18. 영업이익(억) : 'operating_profit'
   19. 영업이익증가율 : 'operating_profit_increasing_rate' 
   20. 당기순이익(억) : 'net_income'
   21. 주당순이익(원) : 'eps'
   22. 보통주배당금(원) : 'dividend'
   23. PER(배) : 'per'
   24. ROE(%) : 'roe'
   25. ROA(%) : 'roa'
   26. PBR(배) : 'pbr'
   27. 유보율(%) : 'reserve_ratio'
   """

"options to choose \n   1. 거래량 : 'quant'\n   2. 시가 : 'open_val'\n   3. 고가 : 'high_val'\n   4. 저가 : 'loq_val' \n   5. 매수호가 : 'ask_buy'\n   6. 매도호가 : 'ask_sell' \n   7. 매수총잔량 : 'buy_total'\n   8. 매도총잔량 : 'sell_total'\n   9. 거래대금(백만) : 'amount' \n   10. 전일거래량 : 'prev_quant'\n   11. 외국인비율 : 'frgn_rate'\n   12. 상장주식수(천주) : 'listed_stock_cnt'\n   13. 시가총액(억) : 'market_sum'\n   14. 자산총계(억) : 'property_total'\n   15. 부채총계(억) : 'debt_total' \n   16. 매출액(억) : 'sales'\n   17. 매출액증가율 : 'sales_increasing_rate'\n   18. 영업이익(억) : 'operating_profit'\n   19. 영업이익증가율 : 'operating_profit_increasing_rate' \n   20. 당기순이익(억) : 'net_income'\n   21. 주당순이익(원) : 'eps'\n   22. 보통주배당금(원) : 'dividend'\n   23. PER(배) : 'per'\n   24. ROE(%) : 'roe'\n   25. ROA(%) : 'roa'\n   26. PBR(배) : 'pbr'\n   27. 유보율(%) : 'reserve_ratio'\n   "

In [3]:
# Requests
req = requests.get(url)
html = req.text

In [4]:
# BeautifulSoup - Making the soup
soup = BeautifulSoup(html, 'lxml')

In [5]:
soup.select('table.type_2 a[href]')

[<a class="tltle" href="/item/main.nhn?code=005930">삼성전자</a>,
 <a href="/item/board.nhn?code=005930"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=000660">SK하이닉스</a>,
 <a href="/item/board.nhn?code=000660"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=005935">삼성전자우</a>,
 <a href="/item/board.nhn?code=005935"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=005380">현대차</a>,
 <a href="/item/board.nhn?code=005380"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=051910">LG화학</a>,
 <a href="/item/board.nhn?code=051910"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=005490">POSCO</a>,
 <a href="/item/board.nhn?code=005490"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=015760">한국전력</a>,
 <a href="/item/board.nhn?code=015760"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=035420">NAVER</a>,
 <a href="/item/board.nhn?code=035420"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=028260">삼성물산</a>,
 <a href="/item/board.nhn?code=028260"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=055550">신한지주</a>,
 <a href="/item/board.nhn?code=055550"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=032830">삼성생명</a>,
 <a href="/item/board.nhn?code=032830"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=105560">KB금융</a>,
 <a href="/item/board.nhn?code=105560"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=207940">삼성바이오로직스</a>,
 <a href="/item/board.nhn?code=207940"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=012330">현대모비스</a>,
 <a href="/item/board.nhn?code=012330"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=017670">SK텔레콤</a>,
 <a href="/item/board.nhn?code=017670"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=034730">SK</a>,
 <a href="/item/board.nhn?code=034730"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=096770">SK이노베이션</a>,
 <a href="/item/board.nhn?code=096770"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=006400">삼성SDI</a>,
 <a href="/item/board.nhn?code=006400"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=003550">LG</a>,
 <a href="/item/board.nhn?code=003550"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=066570">LG전자</a>,
 <a href="/item/board.nhn?code=066570"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=090430">아모레퍼시픽</a>,
 <a href="/item/board.nhn?code=090430"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=033780">KT&amp;G</a>,
 <a href="/item/board.nhn?code=033780"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=051900">LG생활건강</a>,
 <a href="/item/board.nhn?code=051900"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=086790">하나금융지주</a>,
 <a href="/item/board.nhn?code=086790"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=018260">삼성에스디에스</a>,
 <a href="/item/board.nhn?code=018260"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=011170">롯데케미칼</a>,
 <a href="/item/board.nhn?code=011170"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=010950">S-Oil</a>,
 <a href="/item/board.nhn?code=010950"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=000810">삼성화재</a>,
 <a href="/item/board.nhn?code=000810"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=251270">넷마블게임즈</a>,
 <a href="/item/board.nhn?code=251270"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=000270">기아차</a>,
 <a href="/item/board.nhn?code=000270"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=034220">LG디스플레이</a>,
 <a href="/item/board.nhn?code=034220"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=000030">우리은행</a>,
 <a href="/item/board.nhn?code=000030"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=036570">엔씨소프트</a>,
 <a href="/item/board.nhn?code=036570"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=002790">아모레G</a>,
 <a href="/item/board.nhn?code=002790"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=010130">고려아연</a>,
 <a href="/item/board.nhn?code=010130"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=035720">카카오</a>,
 <a href="/item/board.nhn?code=035720"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=009150">삼성전기</a>,
 <a href="/item/board.nhn?code=009150"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=024110">기업은행</a>,
 <a href="/item/board.nhn?code=024110"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=009540">현대중공업</a>,
 <a href="/item/board.nhn?code=009540"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=030200">KT</a>,
 <a href="/item/board.nhn?code=030200"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=035250">강원랜드</a>,
 <a href="/item/board.nhn?code=035250"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=023530">롯데쇼핑</a>,
 <a href="/item/board.nhn?code=023530"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=161390">한국타이어</a>,
 <a href="/item/board.nhn?code=161390"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=021240">코웨이</a>,
 <a href="/item/board.nhn?code=021240"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=267250">현대로보틱스</a>,
 <a href="/item/board.nhn?code=267250"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=004020">현대제철</a>,
 <a href="/item/board.nhn?code=004020"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=018880">한온시스템</a>,
 <a href="/item/board.nhn?code=018880"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=006800">미래에셋대우</a>,
 <a href="/item/board.nhn?code=006800"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=078930">GS</a>,
 <a href="/item/board.nhn?code=078930"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=009830">한화케미칼</a>,
 <a href="/item/board.nhn?code=009830"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>]

In [10]:
soup.find_all('a', 'tltle')

[<a class="tltle" href="/item/main.nhn?code=005930">삼성전자</a>,
 <a class="tltle" href="/item/main.nhn?code=000660">SK하이닉스</a>,
 <a class="tltle" href="/item/main.nhn?code=005935">삼성전자우</a>,
 <a class="tltle" href="/item/main.nhn?code=005380">현대차</a>,
 <a class="tltle" href="/item/main.nhn?code=005490">POSCO</a>,
 <a class="tltle" href="/item/main.nhn?code=015760">한국전력</a>,
 <a class="tltle" href="/item/main.nhn?code=035420">NAVER</a>,
 <a class="tltle" href="/item/main.nhn?code=028260">삼성물산</a>,
 <a class="tltle" href="/item/main.nhn?code=051910">LG화학</a>,
 <a class="tltle" href="/item/main.nhn?code=055550">신한지주</a>,
 <a class="tltle" href="/item/main.nhn?code=012330">현대모비스</a>,
 <a class="tltle" href="/item/main.nhn?code=032830">삼성생명</a>,
 <a class="tltle" href="/item/main.nhn?code=105560">KB금융</a>,
 <a class="tltle" href="/item/main.nhn?code=017670">SK텔레콤</a>,
 <a class="tltle" href="/item/main.nhn?code=034730">SK</a>,
 <a class="tltle" href="/item/main.nhn?code=207940">삼성바이오로직스</a>,
 <a class="tltle" href="/item/main.nhn?code=090430">아모레퍼시픽</a>,
 <a class="tltle" href="/item/main.nhn?code=096770">SK이노베이션</a>,
 <a class="tltle" href="/item/main.nhn?code=033780">KT&amp;G</a>,
 <a class="tltle" href="/item/main.nhn?code=051900">LG생활건강</a>,
 <a class="tltle" href="/item/main.nhn?code=086790">하나금융지주</a>,
 <a class="tltle" href="/item/main.nhn?code=000270">기아차</a>,
 <a class="tltle" href="/item/main.nhn?code=003550">LG</a>,
 <a class="tltle" href="/item/main.nhn?code=000810">삼성화재</a>,
 <a class="tltle" href="/item/main.nhn?code=011170">롯데케미칼</a>,
 <a class="tltle" href="/item/main.nhn?code=018260">삼성에스디에스</a>,
 <a class="tltle" href="/item/main.nhn?code=010950">S-Oil</a>,
 <a class="tltle" href="/item/main.nhn?code=000030">우리은행</a>,
 <a class="tltle" href="/item/main.nhn?code=006400">삼성SDI</a>,
 <a class="tltle" href="/item/main.nhn?code=066570">LG전자</a>,
 <a class="tltle" href="/item/main.nhn?code=251270">넷마블게임즈</a>,
 <a class="tltle" href="/item/main.nhn?code=034220">LG디스플레이</a>,
 <a class="tltle" href="/item/main.nhn?code=002790">아모레G</a>,
 <a class="tltle" href="/item/main.nhn?code=010130">고려아연</a>,
 <a class="tltle" href="/item/main.nhn?code=009540">현대중공업</a>,
 <a class="tltle" href="/item/main.nhn?code=024110">기업은행</a>,
 <a class="tltle" href="/item/main.nhn?code=030200">KT</a>,
 <a class="tltle" href="/item/main.nhn?code=023530">롯데쇼핑</a>,
 <a class="tltle" href="/item/main.nhn?code=036570">엔씨소프트</a>,
 <a class="tltle" href="/item/main.nhn?code=004020">현대제철</a>,
 <a class="tltle" href="/item/main.nhn?code=035720">카카오</a>,
 <a class="tltle" href="/item/main.nhn?code=035250">강원랜드</a>,
 <a class="tltle" href="/item/main.nhn?code=161390">한국타이어</a>,
 <a class="tltle" href="/item/main.nhn?code=021240">코웨이</a>,
 <a class="tltle" href="/item/main.nhn?code=009150">삼성전기</a>,
 <a class="tltle" href="/item/main.nhn?code=267250">현대로보틱스</a>,
 <a class="tltle" href="/item/main.nhn?code=006800">미래에셋대우</a>,
 <a class="tltle" href="/item/main.nhn?code=032640">LG유플러스</a>,
 <a class="tltle" href="/item/main.nhn?code=139480">이마트</a>,
 <a class="tltle" href="/item/main.nhn?code=088350">한화생명</a>]

In [11]:
import re
soup.find_all(href = re.compile("/item/main.nhn?"))

[<a class="tltle" href="/item/main.nhn?code=005930">삼성전자</a>,
 <a class="tltle" href="/item/main.nhn?code=000660">SK하이닉스</a>,
 <a class="tltle" href="/item/main.nhn?code=005935">삼성전자우</a>,
 <a class="tltle" href="/item/main.nhn?code=005380">현대차</a>,
 <a class="tltle" href="/item/main.nhn?code=005490">POSCO</a>,
 <a class="tltle" href="/item/main.nhn?code=015760">한국전력</a>,
 <a class="tltle" href="/item/main.nhn?code=035420">NAVER</a>,
 <a class="tltle" href="/item/main.nhn?code=028260">삼성물산</a>,
 <a class="tltle" href="/item/main.nhn?code=051910">LG화학</a>,
 <a class="tltle" href="/item/main.nhn?code=055550">신한지주</a>,
 <a class="tltle" href="/item/main.nhn?code=012330">현대모비스</a>,
 <a class="tltle" href="/item/main.nhn?code=032830">삼성생명</a>,
 <a class="tltle" href="/item/main.nhn?code=105560">KB금융</a>,
 <a class="tltle" href="/item/main.nhn?code=017670">SK텔레콤</a>,
 <a class="tltle" href="/item/main.nhn?code=034730">SK</a>,
 <a class="tltle" href="/item/main.nhn?code=207940">삼성바이오로직스</a>,
 <a class="tltle" href="/item/main.nhn?code=090430">아모레퍼시픽</a>,
 <a class="tltle" href="/item/main.nhn?code=096770">SK이노베이션</a>,
 <a class="tltle" href="/item/main.nhn?code=033780">KT&amp;G</a>,
 <a class="tltle" href="/item/main.nhn?code=051900">LG생활건강</a>,
 <a class="tltle" href="/item/main.nhn?code=086790">하나금융지주</a>,
 <a class="tltle" href="/item/main.nhn?code=000270">기아차</a>,
 <a class="tltle" href="/item/main.nhn?code=003550">LG</a>,
 <a class="tltle" href="/item/main.nhn?code=000810">삼성화재</a>,
 <a class="tltle" href="/item/main.nhn?code=011170">롯데케미칼</a>,
 <a class="tltle" href="/item/main.nhn?code=018260">삼성에스디에스</a>,
 <a class="tltle" href="/item/main.nhn?code=010950">S-Oil</a>,
 <a class="tltle" href="/item/main.nhn?code=000030">우리은행</a>,
 <a class="tltle" href="/item/main.nhn?code=006400">삼성SDI</a>,
 <a class="tltle" href="/item/main.nhn?code=066570">LG전자</a>,
 <a class="tltle" href="/item/main.nhn?code=251270">넷마블게임즈</a>,
 <a class="tltle" href="/item/main.nhn?code=034220">LG디스플레이</a>,
 <a class="tltle" href="/item/main.nhn?code=002790">아모레G</a>,
 <a class="tltle" href="/item/main.nhn?code=010130">고려아연</a>,
 <a class="tltle" href="/item/main.nhn?code=009540">현대중공업</a>,
 <a class="tltle" href="/item/main.nhn?code=024110">기업은행</a>,
 <a class="tltle" href="/item/main.nhn?code=030200">KT</a>,
 <a class="tltle" href="/item/main.nhn?code=023530">롯데쇼핑</a>,
 <a class="tltle" href="/item/main.nhn?code=036570">엔씨소프트</a>,
 <a class="tltle" href="/item/main.nhn?code=004020">현대제철</a>,
 <a class="tltle" href="/item/main.nhn?code=035720">카카오</a>,
 <a class="tltle" href="/item/main.nhn?code=035250">강원랜드</a>,
 <a class="tltle" href="/item/main.nhn?code=161390">한국타이어</a>,
 <a class="tltle" href="/item/main.nhn?code=021240">코웨이</a>,
 <a class="tltle" href="/item/main.nhn?code=009150">삼성전기</a>,
 <a class="tltle" href="/item/main.nhn?code=267250">현대로보틱스</a>,
 <a class="tltle" href="/item/main.nhn?code=006800">미래에셋대우</a>,
 <a class="tltle" href="/item/main.nhn?code=032640">LG유플러스</a>,
 <a class="tltle" href="/item/main.nhn?code=139480">이마트</a>,
 <a class="tltle" href="/item/main.nhn?code=088350">한화생명</a>]

In [12]:
a = '<a class="tltle" href="/item/main.nhn?code=000030">우리은행</a>'
a.strip('"<>/a').split('=')[-1].split('">')

['000030', '우리은행']

In [13]:
soup.select('a[href*="/item/main.nhn"], td[class^="number"]')

[<a class="tltle" href="/item/main.nhn?code=005930">삼성전자</a>,
 <a class="tltle" href="/item/main.nhn?code=000660">SK하이닉스</a>,
 <a class="tltle" href="/item/main.nhn?code=005935">삼성전자우</a>,
 <a class="tltle" href="/item/main.nhn?code=005380">현대차</a>,
 <a class="tltle" href="/item/main.nhn?code=005490">POSCO</a>,
 <a class="tltle" href="/item/main.nhn?code=015760">한국전력</a>,
 <a class="tltle" href="/item/main.nhn?code=035420">NAVER</a>,
 <a class="tltle" href="/item/main.nhn?code=028260">삼성물산</a>,
 <a class="tltle" href="/item/main.nhn?code=051910">LG화학</a>,
 <a class="tltle" href="/item/main.nhn?code=055550">신한지주</a>,
 <a class="tltle" href="/item/main.nhn?code=012330">현대모비스</a>,
 <a class="tltle" href="/item/main.nhn?code=032830">삼성생명</a>,
 <a class="tltle" href="/item/main.nhn?code=105560">KB금융</a>,
 <a class="tltle" href="/item/main.nhn?code=017670">SK텔레콤</a>,
 <a class="tltle" href="/item/main.nhn?code=034730">SK</a>,
 <a class="tltle" href="/item/main.nhn?code=207940">삼성바이오로직스</a>,
 <a class="tltle" href="/item/main.nhn?code=090430">아모레퍼시픽</a>,
 <a class="tltle" href="/item/main.nhn?code=096770">SK이노베이션</a>,
 <a class="tltle" href="/item/main.nhn?code=033780">KT&amp;G</a>,
 <a class="tltle" href="/item/main.nhn?code=051900">LG생활건강</a>,
 <a class="tltle" href="/item/main.nhn?code=086790">하나금융지주</a>,
 <a class="tltle" href="/item/main.nhn?code=000270">기아차</a>,
 <a class="tltle" href="/item/main.nhn?code=003550">LG</a>,
 <a class="tltle" href="/item/main.nhn?code=000810">삼성화재</a>,
 <a class="tltle" href="/item/main.nhn?code=011170">롯데케미칼</a>,
 <a class="tltle" href="/item/main.nhn?code=018260">삼성에스디에스</a>,
 <a class="tltle" href="/item/main.nhn?code=010950">S-Oil</a>,
 <a class="tltle" href="/item/main.nhn?code=000030">우리은행</a>,
 <a class="tltle" href="/item/main.nhn?code=006400">삼성SDI</a>,
 <a class="tltle" href="/item/main.nhn?code=066570">LG전자</a>,
 <a class="tltle" href="/item/main.nhn?code=251270">넷마블게임즈</a>,
 <a class="tltle" href="/item/main.nhn?code=034220">LG디스플레이</a>,
 <a class="tltle" href="/item/main.nhn?code=002790">아모레G</a>,
 <a class="tltle" href="/item/main.nhn?code=010130">고려아연</a>,
 <a class="tltle" href="/item/main.nhn?code=009540">현대중공업</a>,
 <a class="tltle" href="/item/main.nhn?code=024110">기업은행</a>,
 <a class="tltle" href="/item/main.nhn?code=030200">KT</a>,
 <a class="tltle" href="/item/main.nhn?code=023530">롯데쇼핑</a>,
 <a class="tltle" href="/item/main.nhn?code=036570">엔씨소프트</a>,
 <a class="tltle" href="/item/main.nhn?code=004020">현대제철</a>,
 <a class="tltle" href="/item/main.nhn?code=035720">카카오</a>,
 <a class="tltle" href="/item/main.nhn?code=035250">강원랜드</a>,
 <a class="tltle" href="/item/main.nhn?code=161390">한국타이어</a>,
 <a class="tltle" href="/item/main.nhn?code=021240">코웨이</a>,
 <a class="tltle" href="/item/main.nhn?code=009150">삼성전기</a>,
 <a class="tltle" href="/item/main.nhn?code=267250">현대로보틱스</a>,
 <a class="tltle" href="/item/main.nhn?code=006800">미래에셋대우</a>,
 <a class="tltle" href="/item/main.nhn?code=032640">LG유플러스</a>,
 <a class="tltle" href="/item/main.nhn?code=139480">이마트</a>,
 <a class="tltle" href="/item/main.nhn?code=088350">한화생명</a>,
 <td class="number">2,345,000</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				7,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.30%
 				</span>
 </td>,
 <td class="number">5,000</td>,
 <td class="number">200,007</td>,
 <td class="number">129,768</td>,
 <td class="number">3,043,071</td>,
 <td class="number">2,621,743</td>,
 <td class="number">692,113</td>,
 <td class="number">1.76</td>,
 <td class="number">67,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				600
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.90%
 				</span>
 </td>,
 <td class="number">3,119,691</td>,
 <td class="number">728,002</td>,
 <td class="number">487,762</td>,
 <td class="number">322,160</td>,
 <td class="number">81,925</td>,
 <td class="number">1.97</td>,
 <td class="number">1,937,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				4,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.21%
 				</span>
 </td>,
 <td class="number">14,815</td>,
 <td class="number">18,419</td>,
 <td class="number">356,768</td>,
 <td class="number">N/A</td>,
 <td class="number">1.45</td>,
 <td class="number">144,500</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				500
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.35%
 				</span>
 </td>,
 <td class="number">252,357</td>,
 <td class="number">220,276</td>,
 <td class="number">318,300</td>,
 <td class="number">1,788,359</td>,
 <td class="number">1,064,914</td>,
 <td class="number">0.58</td>,
 <td class="number">330,500</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				3,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.90%
 				</span>
 </td>,
 <td class="number">110,607</td>,
 <td class="number">87,187</td>,
 <td class="number">288,152</td>,
 <td class="number">797,630</td>,
 <td class="number">339,246</td>,
 <td class="number">0.62</td>,
 <td class="number">44,850</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				550
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.24%
 				</span>
 </td>,
 <td class="number">1,346,020</td>,
 <td class="number">641,964</td>,
 <td class="number">287,921</td>,
 <td class="number">1,778,370</td>,
 <td class="number">1,047,865</td>,
 <td class="number">0.40</td>,
 <td class="number">784,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				7,000
 				</span>
 </td>,
 <td class="number">500</td>,
 <td class="number">43,242</td>,
 <td class="number">32,963</td>,
 <td class="number">258,427</td>,
 <td class="number">63,706</td>,
 <td class="number">22,410</td>,
 <td class="number">6.28</td>,
 <td class="number">133,500</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				1,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.74%
 				</span>
 </td>,
 <td class="number">100</td>,
 <td class="number">164,907</td>,
 <td class="number">189,690</td>,
 <td class="number">253,236</td>,
 <td class="number">444,585</td>,
 <td class="number">233,528</td>,
 <td class="number">1.20</td>,
 <td class="number">349,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				5,500
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.60%
 				</span>
 </td>,
 <td class="number">153,737</td>,
 <td class="number">70,592</td>,
 <td class="number">246,367</td>,
 <td class="number">204,871</td>,
 <td class="number">64,361</td>,
 <td class="number">1.81</td>,
 <td class="number">51,900</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				700
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-1.33%
 				</span>
 </td>,
 <td class="number">756,928</td>,
 <td class="number">474,200</td>,
 <td class="number">246,110</td>,
 <td class="number">3,956,803</td>,
 <td class="number">3,639,353</td>,
 <td class="number">0.79</td>,
 <td class="number">246,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.41%
 				</span>
 </td>,
 <td class="number">66,873</td>,
 <td class="number">97,344</td>,
 <td class="number">239,466</td>,
 <td class="number">417,116</td>,
 <td class="number">131,536</td>,
 <td class="number">0.82</td>,
 <td class="number">119,500</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				2,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-1.65%
 				</span>
 </td>,
 <td class="number">245,435</td>,
 <td class="number">200,000</td>,
 <td class="number">239,000</td>,
 <td class="number">2,646,538</td>,
 <td class="number">2,363,454</td>,
 <td class="number">0.81</td>,
 <td class="number">56,500</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				500
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.88%
 				</span>
 </td>,
 <td class="number">448,299</td>,
 <td class="number">418,112</td>,
 <td class="number">236,233</td>,
 <td class="number">3,756,737</td>,
 <td class="number">3,444,123</td>,
 <td class="number">0.73</td>,
 <td class="number">260,000</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				4,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-1.52%
 				</span>
 </td>,
 <td class="number">235,295</td>,
 <td class="number">80,746</td>,
 <td class="number">209,939</td>,
 <td class="number">312,977</td>,
 <td class="number">151,812</td>,
 <td class="number">1.15</td>,
 <td class="number">269,000</td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.37%
 				</span>
 </td>,
 <td class="number">200</td>,
 <td class="number">85,360</td>,
 <td class="number">70,360</td>,
 <td class="number">189,269</td>,
 <td class="number">1,030,473</td>,
 <td class="number">607,206</td>,
 <td class="number">1.16</td>,
 <td class="number">273,000</td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.37%
 				</span>
 </td>,
 <td class="number">2,500</td>,
 <td class="number">88,300</td>,
 <td class="number">66,165</td>,
 <td class="number">180,630</td>,
 <td class="number">75,330</td>,
 <td class="number">34,506</td>,
 <td class="number">4.42</td>,
 <td class="number">280,000</td>,
 <td class="number">
 <span class="tah p11">0</span>
 </td>,
 <td class="number">
 <span class="tah p11">0.00%</span>
 </td>,
 <td class="number">55,302</td>,
 <td class="number">58,458</td>,
 <td class="number">163,684</td>,
 <td class="number">51,816</td>,
 <td class="number">12,849</td>,
 <td class="number">4.98</td>,
 <td class="number">170,500</td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.29%
 				</span>
 </td>,
 <td class="number">146,660</td>,
 <td class="number">92,466</td>,
 <td class="number">157,654</td>,
 <td class="number">325,813</td>,
 <td class="number">142,763</td>,
 <td class="number">0.93</td>,
 <td class="number">114,000</td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.87%
 				</span>
 </td>,
 <td class="number">207,901</td>,
 <td class="number">137,292</td>,
 <td class="number">156,513</td>,
 <td class="number">98,126</td>,
 <td class="number">26,943</td>,
 <td class="number">2.04</td>,
 <td class="number">977,000</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				5,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.51%
 				</span>
 </td>,
 <td class="number">11,189</td>,
 <td class="number">15,618</td>,
 <td class="number">152,590</td>,
 <td class="number">45,022</td>,
 <td class="number">18,813</td>,
 <td class="number">6.46</td>,
 <td class="number">50,000</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				200
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.40%
 				</span>
 </td>,
 <td class="number">510,398</td>,
 <td class="number">296,003</td>,
 <td class="number">148,002</td>,
 <td class="number">3,481,775</td>,
 <td class="number">3,247,875</td>,
 <td class="number">0.66</td>,
 <td class="number">35,350</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				100
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.28%
 				</span>
 </td>,
 <td class="number">443,597</td>,
 <td class="number">405,363</td>,
 <td class="number">143,296</td>,
 <td class="number">508,893</td>,
 <td class="number">243,098</td>,
 <td class="number">0.53</td>,
 <td class="number">80,100</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				300
 				</span>
 </td>,
 <td class="number">212,738</td>,
 <td class="number">172,557</td>,
 <td class="number">138,218</td>,
 <td class="number">194,894</td>,
 <td class="number">52,694</td>,
 <td class="number">1.01</td>,
 <td class="number">286,500</td>,
 <td class="number">48,854</td>,
 <td class="number">47,375</td>,
 <td class="number">135,729</td>,
 <td class="number">682,175</td>,
 <td class="number">572,093</td>,
 <td class="number">1.11</td>,
 <td class="number">393,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				6,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.55%
 				</span>
 </td>,
 <td class="number">159,325</td>,
 <td class="number">34,275</td>,
 <td class="number">134,702</td>,
 <td class="number">158,668</td>,
 <td class="number">64,660</td>,
 <td class="number">1.41</td>,
 <td class="number">172,000</td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.58%
 				</span>
 </td>,
 <td class="number">45,197</td>,
 <td class="number">77,378</td>,
 <td class="number">133,090</td>,
 <td class="number">68,420</td>,
 <td class="number">15,509</td>,
 <td class="number">2.59</td>,
 <td class="number">113,500</td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.44%
 				</span>
 </td>,
 <td class="number">208,274</td>,
 <td class="number">112,583</td>,
 <td class="number">127,781</td>,
 <td class="number">139,590</td>,
 <td class="number">75,674</td>,
 <td class="number">2.07</td>,
 <td class="number">18,300</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				150
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.81%
 				</span>
 </td>,
 <td class="number">636,784</td>,
 <td class="number">676,000</td>,
 <td class="number">123,708</td>,
 <td class="number">3,106,827</td>,
 <td class="number">2,901,368</td>,
 <td class="number">0.60</td>,
 <td class="number">176,500</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				1,500
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.84%
 				</span>
 </td>,
 <td class="number">170,678</td>,
 <td class="number">68,765</td>,
 <td class="number">121,369</td>,
 <td class="number">149,003</td>,
 <td class="number">39,362</td>,
 <td class="number">73,000</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				600
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.82%
 				</span>
 </td>,
 <td class="number">749,552</td>,
 <td class="number">163,648</td>,
 <td class="number">119,463</td>,
 <td class="number">378,553</td>,
 <td class="number">244,985</td>,
 <td class="number">1.10</td>,
 <td class="number">138,500</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				3,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+2.21%
 				</span>
 </td>,
 <td class="number">181,631</td>,
 <td class="number">85,011</td>,
 <td class="number">117,740</td>,
 <td class="number">19,574</td>,
 <td class="number">6,471</td>,
 <td class="number">7.72</td>,
 <td class="number">30,300</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				50
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.16%
 				</span>
 </td>,
 <td class="number">2,056,292</td>,
 <td class="number">357,816</td>,
 <td class="number">108,418</td>,
 <td class="number">248,843</td>,
 <td class="number">114,219</td>,
 <td class="number">0.84</td>,
 <td class="number">125,500</td>,
 <td class="number">90,764</td>,
 <td class="number">82,458</td>,
 <td class="number">103,485</td>,
 <td class="number">70,884</td>,
 <td class="number">15,215</td>,
 <td class="number">3.69</td>,
 <td class="number">501,000</td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.20%
 				</span>
 </td>,
 <td class="number">35,204</td>,
 <td class="number">18,870</td>,
 <td class="number">94,539</td>,
 <td class="number">64,826</td>,
 <td class="number">8,199</td>,
 <td class="number">1.61</td>,
 <td class="number">156,000</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				5,500
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-3.41%
 				</span>
 </td>,
 <td class="number">639,260</td>,
 <td class="number">56,665</td>,
 <td class="number">88,398</td>,
 <td class="number">492,492</td>,
 <td class="number">313,594</td>,
 <td class="number">0.64</td>,
 <td class="number">15,150</td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.66%
 				</span>
 </td>,
 <td class="number">748,895</td>,
 <td class="number">559,979</td>,
 <td class="number">84,837</td>,
 <td class="number">2,568,514</td>,
 <td class="number">2,388,040</td>,
 <td class="number">0.56</td>,
 <td class="number">32,450</td>,
 <td class="number">406,081</td>,
 <td class="number">261,112</td>,
 <td class="number">84,731</td>,
 <td class="number">305,877</td>,
 <td class="number">177,930</td>,
 <td class="number">0.69</td>,
 <td class="number">267,500</td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.19%
 				</span>
 </td>,
 <td class="number">68,676</td>,
 <td class="number">31,491</td>,
 <td class="number">84,238</td>,
 <td class="number">419,159</td>,
 <td class="number">246,519</td>,
 <td class="number">0.48</td>,

In [6]:
# Making a dict to contain all values for Piotroski Universe - To identify Book-to-Market Value and small-to-medium firm
from collections import defaultdict

piotroski_size = defaultdict(list)

In [7]:
stock_ids = soup.select('a[href*="/item/main.nhn"]')

In [8]:
stock_ids

[<a class="tltle" href="/item/main.nhn?code=005930">삼성전자</a>,
 <a class="tltle" href="/item/main.nhn?code=000660">SK하이닉스</a>,
 <a class="tltle" href="/item/main.nhn?code=005935">삼성전자우</a>,
 <a class="tltle" href="/item/main.nhn?code=005380">현대차</a>,
 <a class="tltle" href="/item/main.nhn?code=051910">LG화학</a>,
 <a class="tltle" href="/item/main.nhn?code=005490">POSCO</a>,
 <a class="tltle" href="/item/main.nhn?code=015760">한국전력</a>,
 <a class="tltle" href="/item/main.nhn?code=035420">NAVER</a>,
 <a class="tltle" href="/item/main.nhn?code=028260">삼성물산</a>,
 <a class="tltle" href="/item/main.nhn?code=055550">신한지주</a>,
 <a class="tltle" href="/item/main.nhn?code=032830">삼성생명</a>,
 <a class="tltle" href="/item/main.nhn?code=105560">KB금융</a>,
 <a class="tltle" href="/item/main.nhn?code=207940">삼성바이오로직스</a>,
 <a class="tltle" href="/item/main.nhn?code=012330">현대모비스</a>,
 <a class="tltle" href="/item/main.nhn?code=017670">SK텔레콤</a>,
 <a class="tltle" href="/item/main.nhn?code=034730">SK</a>,
 <a class="tltle" href="/item/main.nhn?code=096770">SK이노베이션</a>,
 <a class="tltle" href="/item/main.nhn?code=006400">삼성SDI</a>,
 <a class="tltle" href="/item/main.nhn?code=003550">LG</a>,
 <a class="tltle" href="/item/main.nhn?code=066570">LG전자</a>,
 <a class="tltle" href="/item/main.nhn?code=090430">아모레퍼시픽</a>,
 <a class="tltle" href="/item/main.nhn?code=033780">KT&amp;G</a>,
 <a class="tltle" href="/item/main.nhn?code=051900">LG생활건강</a>,
 <a class="tltle" href="/item/main.nhn?code=086790">하나금융지주</a>,
 <a class="tltle" href="/item/main.nhn?code=018260">삼성에스디에스</a>,
 <a class="tltle" href="/item/main.nhn?code=011170">롯데케미칼</a>,
 <a class="tltle" href="/item/main.nhn?code=010950">S-Oil</a>,
 <a class="tltle" href="/item/main.nhn?code=000810">삼성화재</a>,
 <a class="tltle" href="/item/main.nhn?code=251270">넷마블게임즈</a>,
 <a class="tltle" href="/item/main.nhn?code=000270">기아차</a>,
 <a class="tltle" href="/item/main.nhn?code=034220">LG디스플레이</a>,
 <a class="tltle" href="/item/main.nhn?code=000030">우리은행</a>,
 <a class="tltle" href="/item/main.nhn?code=036570">엔씨소프트</a>,
 <a class="tltle" href="/item/main.nhn?code=002790">아모레G</a>,
 <a class="tltle" href="/item/main.nhn?code=010130">고려아연</a>,
 <a class="tltle" href="/item/main.nhn?code=035720">카카오</a>,
 <a class="tltle" href="/item/main.nhn?code=009150">삼성전기</a>,
 <a class="tltle" href="/item/main.nhn?code=024110">기업은행</a>,
 <a class="tltle" href="/item/main.nhn?code=009540">현대중공업</a>,
 <a class="tltle" href="/item/main.nhn?code=030200">KT</a>,
 <a class="tltle" href="/item/main.nhn?code=035250">강원랜드</a>,
 <a class="tltle" href="/item/main.nhn?code=023530">롯데쇼핑</a>,
 <a class="tltle" href="/item/main.nhn?code=161390">한국타이어</a>,
 <a class="tltle" href="/item/main.nhn?code=021240">코웨이</a>,
 <a class="tltle" href="/item/main.nhn?code=267250">현대로보틱스</a>,
 <a class="tltle" href="/item/main.nhn?code=004020">현대제철</a>,
 <a class="tltle" href="/item/main.nhn?code=018880">한온시스템</a>,
 <a class="tltle" href="/item/main.nhn?code=006800">미래에셋대우</a>,
 <a class="tltle" href="/item/main.nhn?code=078930">GS</a>,
 <a class="tltle" href="/item/main.nhn?code=009830">한화케미칼</a>]

In [45]:
stock_id_ls = []
stock_name_ls = [] 
for id in stock_ids: 
    stock_id_ls.append(str(id).strip('"<>/a').split('=')[-1].split('">')[0])
    stock_name_ls.append(str(id).strip('"<>/a').split('=')[-1].split('">')[1])

In [10]:
len(stock_id_ls)

50

In [11]:
len(stock_name_ls)

50

In [39]:
# Convert stock ids & names lists to Pandas DF 
df_piotroski = pd.DataFrame({'id' : stock_id_ls, 'name': stock_name_ls}, columns = ['id', 'name', 'market_type', 'quant', 'market_sum', 'property_total', 'debt_total', 'listed_stock_cnt', 'pbr', 'face_value',])

In [46]:
df_piotroski['market_type'] = 1
# KOSPI '1' , KOSDAQ '2'

In [47]:
df_piotroski

,id,name,market_type,quant,market_sum,property_total,debt_total,listed_stock_cnt,pbr,face_value
0,005930,삼성전자,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,000660,SK하이닉스,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,005935,삼성전자우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,005380,현대차,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,051910,LG화학,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,005490,POSCO,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,015760,한국전력,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,035420,NAVER,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,028260,삼성물산,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,055550,신한지주,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,032830,삼성생명,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,105560,KB금융,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,207940,삼성바이오로직스,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,012330,현대모비스,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,017670,SK텔레콤,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,034730,SK,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,096770,SK이노베이션,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,006400,삼성SDI,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,003550,LG,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,066570,LG전자,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,090430,아모레퍼시픽,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,033780,KT&amp;G,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,051900,LG생활건강,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,086790,하나금융지주,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,018260,삼성에스디에스,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,011170,롯데케미칼,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,010950,S-Oil,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,000810,삼성화재,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,251270,넷마블게임즈,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,000270,기아차,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1324,001065,JW중외제약우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1325,004835,덕성우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1326,001527,동양2우B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1327,014285,금강공업우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1328,090355,노루페인트우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1329,005965,동부건설우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1330,000995,동부하이텍1우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1331,227560,TIGER 200 생활소비재,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1332,004985,성신양회우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1333,000325,노루홀딩스우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1334,016385,동부제철우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1335,001067,JW중외제약2우B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1336,227550,TIGER 200 산업재,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1337,161500,ARIRANG 경기주도주,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1338,253160,ARIRANG 200선물인버스2X,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1339,002785,진흥기업우B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1340,000547,흥국화재2우B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1341,140580,KBSTAR 우량업종,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1342,139310,TIGER 금속선물(H),1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1343,000227,유유제약2우B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1344,001799,대한제당3우B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1345,157510,TIGER 자동차,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1346,013367,일성건설2우B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1347,008355,남선알미우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1348,002787,진흥기업2우B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1349,004989,성신양회3우B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1350,001529,동양3우B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1351,161490,ARIRANG 경기방어주,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1352,004987,성신양회2우B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1353,000327,노루홀딩스2우B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
piotroski_univ_sets = soup.select('td[class^="number"]')
piotroski_univ_sets

[<td class="number">2,520,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				5,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.20%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">211,015</td>, <td class="number">129,768</td>, <td class="number">3,270,166</td>, <td class="number">2,621,743</td>, <td class="number">692,113</td>, <td class="number">1.89</td>, <td class="number">77,200</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				400
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.52%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">2,709,690</td>, <td class="number">728,002</td>, <td class="number">562,018</td>, <td class="number">322,160</td>, <td class="number">81,925</td>, <td class="number">2.27</td>, <td class="number">2,045,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				10,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.49%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">29,544</td>, <td class="number">18,419</td>, <td class="number">376,660</td>, <td class="number">N/A</td>, <td class="number">N/A</td>, <td class="number">1.54</td>, <td class="number">136,500</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-0.36%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">369,293</td>, <td class="number">220,276</td>, <td class="number">300,677</td>, <td class="number">1,788,359</td>, <td class="number">1,064,914</td>, <td class="number">0.55</td>, <td class="number">401,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				6,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-1.47%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">304,518</td>, <td class="number">70,592</td>, <td class="number">283,075</td>, <td class="number">204,871</td>, <td class="number">64,361</td>, <td class="number">2.08</td>, <td class="number">312,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				11,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-3.55%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">450,614</td>, <td class="number">87,187</td>, <td class="number">272,023</td>, <td class="number">797,630</td>, <td class="number">339,246</td>, <td class="number">0.59</td>, <td class="number">41,200</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				150
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.37%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">786,210</td>, <td class="number">641,964</td>, <td class="number">264,489</td>, <td class="number">1,778,370</td>, <td class="number">1,047,865</td>, <td class="number">0.37</td>, <td class="number">760,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				5,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-0.65%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">97,112</td>, <td class="number">32,963</td>, <td class="number">250,516</td>, <td class="number">63,706</td>, <td class="number">22,410</td>, <td class="number">6.09</td>, <td class="number">127,500</td>, <td class="number">
 <span class="tah p11">0</span>
 </td>, <td class="number">
 <span class="tah p11">0.00%</span>
 </td>, <td class="number">100</td>, <td class="number">454,229</td>, <td class="number">189,690</td>, <td class="number">241,855</td>, <td class="number">444,585</td>, <td class="number">233,528</td>, <td class="number">1.15</td>, <td class="number">50,900</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,200
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+2.41%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">1,145,662</td>, <td class="number">474,200</td>, <td class="number">241,368</td>, <td class="number">3,956,803</td>, <td class="number">3,639,353</td>, <td class="number">0.78</td>, <td class="number">117,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.30%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">199,162</td>, <td class="number">200,000</td>, <td class="number">234,000</td>, <td class="number">2,646,538</td>, <td class="number">2,363,454</td>, <td class="number">0.79</td>, <td class="number">54,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				400
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.75%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">855,872</td>, <td class="number">418,112</td>, <td class="number">225,780</td>, <td class="number">3,756,737</td>, <td class="number">3,444,123</td>, <td class="number">0.69</td>, <td class="number">326,500</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				2,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.77%
 				</span>
 </td>, <td class="number">2,500</td>, <td class="number">374,923</td>, <td class="number">66,165</td>, <td class="number">216,029</td>, <td class="number">75,330</td>, <td class="number">34,506</td>, <td class="number">5.29</td>, <td class="number">216,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				2,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.17%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">233,988</td>, <td class="number">97,344</td>, <td class="number">210,263</td>, <td class="number">417,116</td>, <td class="number">131,536</td>, <td class="number">0.72</td>, <td class="number">253,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				11,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+4.55%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">253,797</td>, <td class="number">80,746</td>, <td class="number">204,287</td>, <td class="number">312,977</td>, <td class="number">151,812</td>, <td class="number">1.12</td>, <td class="number">263,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				2,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.77%
 				</span>
 </td>, <td class="number">200</td>, <td class="number">112,509</td>, <td class="number">70,360</td>, <td class="number">185,048</td>, <td class="number">1,030,473</td>, <td class="number">607,206</td>, <td class="number">1.13</td>, <td class="number">189,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				7,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-3.57%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">499,883</td>, <td class="number">92,466</td>, <td class="number">174,760</td>, <td class="number">325,813</td>, <td class="number">142,763</td>, <td class="number">1.03</td>, <td class="number">214,500</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				4,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+2.14%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">384,033</td>, <td class="number">68,765</td>, <td class="number">147,500</td>, <td class="number">149,003</td>, <td class="number">39,362</td>, <td class="number">1.35</td>, <td class="number">85,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,400
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.67%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">410,892</td>, <td class="number">172,557</td>, <td class="number">146,674</td>, <td class="number">194,894</td>, <td class="number">52,694</td>, <td class="number">1.08</td>, <td class="number">89,500</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,600
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.82%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">2,644,097</td>, <td class="number">163,648</td>, <td class="number">146,465</td>, <td class="number">378,553</td>, <td class="number">244,985</td>, <td class="number">1.34</td>, <td class="number">250,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				10,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-3.85%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">484,823</td>, <td class="number">58,458</td>, <td class="number">146,146</td>, <td class="number">51,816</td>, <td class="number">12,849</td>, <td class="number">4.45</td>, <td class="number">106,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				4,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+4.43%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">485,524</td>, <td class="number">137,292</td>, <td class="number">145,530</td>, <td class="number">98,126</td>, <td class="number">26,943</td>, <td class="number">1.90</td>, <td class="number">909,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				10,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-1.09%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">32,048</td>, <td class="number">15,618</td>, <td class="number">141,969</td>, <td class="number">45,022</td>, <td class="number">18,813</td>, <td class="number">6.01</td>, <td class="number">46,050</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				300
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.66%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">711,958</td>, <td class="number">296,003</td>, <td class="number">136,309</td>, <td class="number">3,481,775</td>, <td class="number">3,247,875</td>, <td class="number">0.61</td>, <td class="number">174,500</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.87%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">79,064</td>, <td class="number">77,378</td>, <td class="number">135,024</td>, <td class="number">68,420</td>, <td class="number">15,509</td>, <td class="number">2.63</td>, <td class="number">387,500</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				21,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-5.14%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">300,594</td>, <td class="number">34,275</td>, <td class="number">132,817</td>, <td class="number">158,668</td>, <td class="number">64,660</td>, <td class="number">1.39</td>, <td class="number">116,500</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				4,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-3.72%
 				</span>
 </td>, <td class="number">2,500</td>, <td class="number">602,361</td>, <td class="number">112,583</td>, <td class="number">131,159</td>, <td class="number">139,590</td>, <td class="number">75,674</td>, <td class="number">2.12</td>, <td class="number">271,500</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				6,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+2.26%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">67,037</td>, <td class="number">47,375</td>, <td class="number">128,623</td>, <td class="number">682,175</td>, <td class="number">572,093</td>, <td class="number">1.05</td>, <td class="number">150,500</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.67%
 				</span>
 </td>, <td class="number">100</td>, <td class="number">173,309</td>, <td class="number">85,018</td>, <td class="number">127,952</td>, <td class="number">19,574</td>, <td class="number">6,471</td>, <td class="number">8.39</td>, <td class="number">30,900</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				300
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.98%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">1,111,612</td>, <td class="number">405,363</td>, <td class="number">125,257</td>, <td class="number">508,893</td>, <td class="number">243,098</td>, <td class="number">0.47</td>, <td class="number">33,800</td>, <td class="number">
 <span class="tah p11">0</span>
 </td>, <td class="number">
 <span class="tah p11">0.00%</span>
 </td>, <td class="number">5,000</td>, <td class="number">4,294,556</td>, <td class="number">357,816</td>, <td class="number">120,942</td>, <td class="number">248,843</td>, <td class="number">114,219</td>, <td class="number">0.93</td>, <td class="number">17,650</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				200
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.15%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">1,380,834</td>, <td class="number">676,000</td>, <td class="number">119,314</td>, <td class="number">3,106,827</td>, <td class="number">2,901,368</td>, <td class="number">0.58</td>, <td class="number">468,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				10,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-2.19%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">320,754</td>, <td class="number">21,939</td>, <td class="number">102,675</td>, <td class="number">23,608</td>, <td class="number">4,653</td>, <td class="number">5.27</td>, <td class="number">122,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				2,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-1.61%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">130,217</td>, <td class="number">82,458</td>, <td class="number">100,599</td>, <td class="number">70,884</td>, <td class="number">15,215</td>, <td class="number">3.59</td>, <td class="number">504,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				11,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-2.14%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">53,951</td>, <td class="number">18,870</td>, <td class="number">95,105</td>, <td class="number">64,826</td>, <td class="number">8,199</td>, <td class="number">1.61</td>, <td class="number">135,500</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				3,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+2.65%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">1,143,487</td>, <td class="number">67,793</td>, <td class="number">91,859</td>, <td class="number">54,841</td>, <td class="number">17,812</td>, <td class="number">2.67</td>, <td class="number">112,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				4,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+3.70%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">1,004,049</td>, <td class="number">74,694</td>, <td class="number">83,657</td>, <td class="number">76,626</td>, <td class="number">33,250</td>, <td class="number">2.00</td>, <td class="number">14,750</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				300
 				</span>

In [15]:
all_number_classes = []
for item in piotroski_univ_sets:
    all_number_classes.append(item.string)

In [16]:
all_number_classes

['2,520,000',
 None,
 None,
 '5,000',
 '211,015',
 '129,768',
 '3,270,166',
 '2,621,743',
 '692,113',
 '1.89',
 '77,200',
 None,
 None,
 '5,000',
 '2,709,690',
 '728,002',
 '562,018',
 '322,160',
 '81,925',
 '2.27',
 '2,045,000',
 None,
 None,
 '5,000',
 '29,544',
 '18,419',
 '376,660',
 'N/A',
 'N/A',
 '1.54',
 '136,500',
 None,
 None,
 '5,000',
 '369,293',
 '220,276',
 '300,677',
 '1,788,359',
 '1,064,914',
 '0.55',
 '401,000',
 None,
 None,
 '5,000',
 '304,518',
 '70,592',
 '283,075',
 '204,871',
 '64,361',
 '2.08',
 '312,000',
 None,
 None,
 '5,000',
 '450,614',
 '87,187',
 '272,023',
 '797,630',
 '339,246',
 '0.59',
 '41,200',
 None,
 None,
 '5,000',
 '786,210',
 '641,964',
 '264,489',
 '1,778,370',
 '1,047,865',
 '0.37',
 '760,000',
 None,
 None,
 '500',
 '97,112',
 '32,963',
 '250,516',
 '63,706',
 '22,410',
 '6.09',
 '127,500',
 None,
 None,
 '100',
 '454,229',
 '189,690',
 '241,855',
 '444,585',
 '233,528',
 '1.15',
 '50,900',
 None,
 None,
 '5,000',
 '1,145,662',
 '474,200',
 '241,368',
 '3,956,803',
 '3,639,353',
 '0.78',
 '117,000',
 None,
 None,
 '500',
 '199,162',
 '200,000',
 '234,000',
 '2,646,538',
 '2,363,454',
 '0.79',
 '54,000',
 None,
 None,
 '5,000',
 '855,872',
 '418,112',
 '225,780',
 '3,756,737',
 '3,444,123',
 '0.69',
 '326,500',
 None,
 None,
 '2,500',
 '374,923',
 '66,165',
 '216,029',
 '75,330',
 '34,506',
 '5.29',
 '216,000',
 None,
 None,
 '5,000',
 '233,988',
 '97,344',
 '210,263',
 '417,116',
 '131,536',
 '0.72',
 '253,000',
 None,
 None,
 '500',
 '253,797',
 '80,746',
 '204,287',
 '312,977',
 '151,812',
 '1.12',
 '263,000',
 None,
 None,
 '200',
 '112,509',
 '70,360',
 '185,048',
 '1,030,473',
 '607,206',
 '1.13',
 '189,000',
 None,
 None,
 '5,000',
 '499,883',
 '92,466',
 '174,760',
 '325,813',
 '142,763',
 '1.03',
 '214,500',
 None,
 None,
 '5,000',
 '384,033',
 '68,765',
 '147,500',
 '149,003',
 '39,362',
 '1.35',
 '85,000',
 None,
 None,
 '5,000',
 '410,892',
 '172,557',
 '146,674',
 '194,894',
 '52,694',
 '1.08',
 '89,500',
 None,
 None,
 '5,000',
 '2,644,097',
 '163,648',
 '146,465',
 '378,553',
 '244,985',
 '1.34',
 '250,000',
 None,
 None,
 '500',
 '484,823',
 '58,458',
 '146,146',
 '51,816',
 '12,849',
 '4.45',
 '106,000',
 None,
 None,
 '5,000',
 '485,524',
 '137,292',
 '145,530',
 '98,126',
 '26,943',
 '1.90',
 '909,000',
 None,
 None,
 '5,000',
 '32,048',
 '15,618',
 '141,969',
 '45,022',
 '18,813',
 '6.01',
 '46,050',
 None,
 None,
 '5,000',
 '711,958',
 '296,003',
 '136,309',
 '3,481,775',
 '3,247,875',
 '0.61',
 '174,500',
 None,
 None,
 '500',
 '79,064',
 '77,378',
 '135,024',
 '68,420',
 '15,509',
 '2.63',
 '387,500',
 None,
 None,
 '5,000',
 '300,594',
 '34,275',
 '132,817',
 '158,668',
 '64,660',
 '1.39',
 '116,500',
 None,
 None,
 '2,500',
 '602,361',
 '112,583',
 '131,159',
 '139,590',
 '75,674',
 '2.12',
 '271,500',
 None,
 None,
 '500',
 '67,037',
 '47,375',
 '128,623',
 '682,175',
 '572,093',
 '1.05',
 '150,500',
 None,
 None,
 '100',
 '173,309',
 '85,018',
 '127,952',
 '19,574',
 '6,471',
 '8.39',
 '30,900',
 None,
 None,
 '5,000',
 '1,111,612',
 '405,363',
 '125,257',
 '508,893',
 '243,098',
 '0.47',
 '33,800',
 None,
 None,
 '5,000',
 '4,294,556',
 '357,816',
 '120,942',
 '248,843',
 '114,219',
 '0.93',
 '17,650',
 None,
 None,
 '5,000',
 '1,380,834',
 '676,000',
 '119,314',
 '3,106,827',
 '2,901,368',
 '0.58',
 '468,000',
 None,
 None,
 '500',
 '320,754',
 '21,939',
 '102,675',
 '23,608',
 '4,653',
 '5.27',
 '122,000',
 None,
 None,
 '500',
 '130,217',
 '82,458',
 '100,599',
 '70,884',
 '15,215',
 '3.59',
 '504,000',
 None,
 None,
 '5,000',
 '53,951',
 '18,870',
 '95,105',
 '64,826',
 '8,199',
 '1.61',
 '135,500',
 None,
 None,
 '500',
 '1,143,487',
 '67,793',
 '91,859',
 '54,841',
 '17,812',
 '2.67',
 '112,000',
 None,
 None,
 '5,000',
 '1,004,049',
 '74,694',
 '83,657',
 '76,626',
 '33,250',
 '2.00',
 '14,750',
 None,
 None,
 '5,000',
 '1,245,178',
 '559,979',
 '82,597',
 '2,568,514',
 '2,388,040',
 '0.54',
 '141,000',
 None,
 None,
 '5,000',
 '391,944',
 '56,665',
 '79,898',
 '492,492',
 '313,594',
 '0.58',
 '29,400',
 None,
 None,
 '5,000',
 '879,464',
 '261,112',
 '76,767',
 '305,877',
 '177,930',
 '0.63',
 '35,700',
 None,
 None,
 '500',
 '178,462',
 '213,940',
 '76,377',
 '39,790',
 '7,263',
 '2.23',
 '238,500',
 None,
 None,
 '5,000',
 '542,080',
 '31,491',
 '75,106',
 '419,159',
 '246,519',
 '0.43',
 '59,800',
 None,
 None,
 '500',
 '207,272',
 '123,875',
 '74,077',
 '96,220',
 '36,605',
 '1.24',
 '97,400',
 None,
 None,
 '500',
 '152,061',
 '74,818',
 '72,873',
 '19,677',
 '7,844',
 '6.04',
 '435,500',
 None,
 None,
 '5,000',
 '136,597',
 '16,287',
 '70,928',
 'N/A',
 'N/A',
 'N/A',
 '52,600',
 None,
 None,
 '5,000',
 '470,239',
 '133,446',
 '70,192',
 '323,893',
 '160,256',
 '0.43',
 '12,800',
 None,
 None,
 '100',
 '2,494,066',
 '533,800',
 '68,326',
 '38,597',
 '19,748',
 '3.74',
 '10,200',
 None,
 None,
 '5,000',
 '3,122,689',
 '666,316',
 '67,964',
 '572,678',
 '506,020',
 '0.80',
 '67,100',
 None,
 None,
 '5,000',
 '298,513',
 '92,915',
 '62,346',
 '203,412',
 '114,209',
 '0.91',
 '37,350',
 None,
 None,
 '5,000',
 '605,086',
 '164,809',
 '61,556',
 '138,179',
 '83,496',
 '1.16']

In [17]:
# Titles for each number idex
"""1. present_value = 현재가
   2. none
   3. none
   4. face_value = 액면가
   5. quant = 거래량
   6. listed_stock_cnt = 상장주식수
   7. market_sum = 시가총액 
   8. property_total = 자산총액 
   9. debt_total = 부채총액 
   10. pbr = PBR 
   """

# Slicing and creating an individual list for each category 
present_value = all_number_classes[::10]
face_value = all_number_classes[3::10]
quant = all_number_classes[4::10]
listed_stock_cnt = all_number_classes[5::10]
market_sum = all_number_classes[6::10] 
property_total = all_number_classes[7::10]
debt_total = all_number_classes[8::10]
pbr = all_number_classes[9::10]

In [18]:
# Put each category list to DF
df_piotroski['present_value'] = present_value
df_piotroski['quant'] = quant
df_piotroski['property_total'] = property_total
df_piotroski['debt_total'] = debt_total
df_piotroski['listed_stock_cnt'] = listed_stock_cnt
df_piotroski['pbr'] = pbr
df_piotroski['market_sum'] = market_sum
df_piotroski['face_value'] = face_value

In [19]:
df_piotroski

,id,name,quant,market_sum,property_total,debt_total,listed_stock_cnt,pbr,face_value,present_value
0,005930,삼성전자,"211,015","3,270,166","2,621,743","692,113","129,768",1.89,"5,000","2,520,000"
1,000660,SK하이닉스,"2,709,690","562,018","322,160","81,925","728,002",2.27,"5,000","77,200"
2,005935,삼성전자우,"29,544","376,660",N/A,N/A,"18,419",1.54,"5,000","2,045,000"
3,005380,현대차,"369,293","300,677","1,788,359","1,064,914","220,276",0.55,"5,000","136,500"
4,051910,LG화학,"304,518","283,075","204,871","64,361","70,592",2.08,"5,000","401,000"
5,005490,POSCO,"450,614","272,023","797,630","339,246","87,187",0.59,"5,000","312,000"
6,015760,한국전력,"786,210","264,489","1,778,370","1,047,865","641,964",0.37,"5,000","41,200"
7,035420,NAVER,"97,112","250,516","63,706","22,410","32,963",6.09,500,"760,000"
8,028260,삼성물산,"454,229","241,855","444,585","233,528","189,690",1.15,100,"127,500"
9,055550,신한지주,"1,145,662","241,368","3,956,803","3,639,353","474,200",0.78,"5,000","50,900"
10,032830,삼성생명,"199,162","234,000","2,646,538","2,363,454","200,000",0.79,500,"117,000"
11,105560,KB금융,"855,872","225,780","3,756,737","3,444,123","418,112",0.69,"5,000","54,000"
12,207940,삼성바이오로직스,"374,923","216,029","75,330","34,506","66,165",5.29,"2,500","326,500"
13,012330,현대모비스,"233,988","210,263","417,116","131,536","97,344",0.72,"5,000","216,000"
14,017670,SK텔레콤,"253,797","204,287","312,977","151,812","80,746",1.12,500,"253,000"
15,034730,SK,"112,509","185,048","1,030,473","607,206","70,360",1.13,200,"263,000"
16,096770,SK이노베이션,"499,883","174,760","325,813","142,763","92,466",1.03,"5,000","189,000"
17,006400,삼성SDI,"384,033","147,500","149,003","39,362","68,765",1.35,"5,000","214,500"
18,003550,LG,"410,892","146,674","194,894","52,694","172,557",1.08,"5,000","85,000"
19,066570,LG전자,"2,644,097","146,465","378,553","244,985","163,648",1.34,"5,000","89,500"
20,090430,아모레퍼시픽,"484,823","146,146","51,816","12,849","58,458",4.45,500,"250,000"
21,033780,KT&amp;G,"485,524","145,530","98,126","26,943","137,292",1.90,"5,000","106,000"
22,051900,LG생활건강,"32,048","141,969","45,022","18,813","15,618",6.01,"5,000","909,000"
23,086790,하나금융지주,"711,958","136,309","3,481,775","3,247,875","296,003",0.61,"5,000","46,050"
24,018260,삼성에스디에스,"79,064","135,024","68,420","15,509","77,378",2.63,500,"174,500"
25,011170,롯데케미칼,"300,594","132,817","158,668","64,660","34,275",1.39,"5,000","387,500"
26,010950,S-Oil,"602,361","131,159","139,590","75,674","112,583",2.12,"2,500","116,500"
27,000810,삼성화재,"67,037","128,623","682,175","572,093","47,375",1.05,500,"271,500"
28,251270,넷마블게임즈,"173,309","127,952","19,574","6,471","85,018",8.39,100,"150,500"
29,000270,기아차,"1,111,612","125,257","508,893","243,098","405,363",0.47,"5,000","30,900"
30,034220,LG디스플레이,"4,294,556","120,942","248,843","114,219","357,816",0.93,"5,000","33,800"
31,000030,우리은행,"1,380,834","119,314","3,106,827","2,901,368","676,000",0.58,"5,000","17,650"
32,036570,엔씨소프트,"320,754","102,675","23,608","4,653","21,939",5.27,500,"468,000"
33,002790,아모레G,"130,217","100,599","70,884","15,215","82,458",3.59,500,"122,000"
34,010130,고려아연,"53,951","95,105","64,826","8,199","18,870",1.61,"5,000","504,000"
35,035720,카카오,"1,143,487","91,859","54,841","17,812","67,793",2.67,500,"135,500"
36,009150,삼성전기,"1,004,049","83,657","76,626","33,250","74,694",2.00,"5,000","112,000"
37,024110,기업은행,"1,245,178","82,597","2,568,514","2,388,040","559,979",0.54,"5,000","14,750"
38,009540,현대중공업,"391,944","79,898","492,492","313,594","56,665",0.58,"5,000","141,000"
39,030200,KT,"879,464","76,767","305,877","177,930","261,112",0.63,"5,000","29,400"
40,035250,강원랜드,"178,462","76,377","39,790","7,263","213,940",2.23,500,"35,700"
41,023530,롯데쇼핑,"542,080","75,106","419,159","246,519","31,491",0.43,"5,000","238,500"
42,161390,한국타이어,"207,272","74,077","96,220","36,605","123,875",1.24,500,"59,800"
43,021240,코웨이,"152,061","72,873","19,677","7,844","74,818",6.04,500,"97,400"
44,267250,현대로보틱스,"136,597","70,928",N/A,N/A,"16,287",N/A,"5,000","435,500"
45,004020,현대제철,"470,239","70,192","323,893","160,256","133,446",0.43,"5,000","52,600"
46,018880,한온시스템,"2,494,066","68,326","38,597","19,748","533,800",3.74,100,"12,800"
47,006800,미래에셋대우,"3,122,689","67,964","572,678","506,020","666,316",0.80,"5,000","10,200"
48,078930,GS,"298,513","62,346","203,412","114,209","92,915",0.91,"5,000","67,100"
49,009830,한화케미칼,"605,086","61,556","138,179","83,496","164,809",1.16,"5,000","37,350"

#### ----- BREAK -----

##### Part II : Flipping pages 1 ~ 27

In [20]:
# Looping!

page_num = 1 # KOSPI 27 pages

stock_id_ls = []
stock_name_ls = [] 

all_number_classes = [] 

for num in range(1, page_num + 28): 
    url_p = "http://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn%3Fsosok%3D{0}%26page%3D{1}&fieldIds={2}&fieldIds={3}&fieldIds={4}&fieldIds={5}&fieldIds={6}&fieldIds={7}".format('0',
                                                                                                                                                                                                                                                                   num, 
                                                                                                                                                                                                                                                                   'quant',
                                                                                                                                                                                                                                                                   'listed_stock_cnt',
                                                                                                                                                                                                                                                                   'market_sum',
                                                                                                                                                                                                                                                                   'property_total',
                                                                                                                                                                                                                                                                   'debt_total',
                                                                                                                                                                                                                                                                   'pbr')
    
    r = requests.get(url_p)
    html = r.text 
    
    soup = BeautifulSoup(html, 'lxml')
    
    stock_ids = soup.select('a[href*="/item/main.nhn"]')
    piotroski_univ_sets = soup.select('td[class^="number"]')
    
    # Looping stock ids and names 
    for id in stock_ids: 
        stock_id_ls.append(str(id).strip('"<>/a').split('=')[-1].split('">')[0])
        stock_name_ls.append(str(id).strip('"<>/a').split('=')[-1].split('">')[1])
        
    # Looping Number Classes for each stock    
    for item in piotroski_univ_sets: 
        all_number_classes.append(item.string)

In [21]:
# Convert stock ids & names lists to Pandas DF 
df_piotroski = pd.DataFrame({'id' : stock_id_ls, 'name': stock_name_ls}, columns = ['id', 'name', 'quant', 'market_sum', 'property_total', 'debt_total', 'listed_stock_cnt', 'pbr', 'face_value',])

# Slicing and creating an individual list for each category 
present_value = all_number_classes[::10]
face_value = all_number_classes[3::10]
quant = all_number_classes[4::10]
listed_stock_cnt = all_number_classes[5::10]
market_sum = all_number_classes[6::10] 
property_total = all_number_classes[7::10]
debt_total = all_number_classes[8::10]
pbr = all_number_classes[9::10] 

# Put each category list to DF
df_piotroski['present_value'] = present_value
df_piotroski['quant'] = quant
df_piotroski['property_total'] = property_total
df_piotroski['debt_total'] = debt_total
df_piotroski['listed_stock_cnt'] = listed_stock_cnt
df_piotroski['pbr'] = pbr
df_piotroski['market_sum'] = market_sum
df_piotroski['face_value'] = face_value

In [22]:
df_piotroski

,id,name,quant,market_sum,property_total,debt_total,listed_stock_cnt,pbr,face_value,present_value
0,005930,삼성전자,"211,015","3,270,166","2,621,743","692,113","129,768",1.89,"5,000","2,520,000"
1,000660,SK하이닉스,"2,709,690","562,018","322,160","81,925","728,002",2.27,"5,000","77,200"
2,005935,삼성전자우,"29,544","376,660",N/A,N/A,"18,419",1.54,"5,000","2,045,000"
3,005380,현대차,"369,293","300,677","1,788,359","1,064,914","220,276",0.55,"5,000","136,500"
4,051910,LG화학,"304,518","283,075","204,871","64,361","70,592",2.08,"5,000","401,000"
5,005490,POSCO,"450,614","272,023","797,630","339,246","87,187",0.59,"5,000","312,000"
6,015760,한국전력,"786,210","264,489","1,778,370","1,047,865","641,964",0.37,"5,000","41,200"
7,035420,NAVER,"97,112","250,516","63,706","22,410","32,963",6.09,500,"760,000"
8,028260,삼성물산,"454,229","241,855","444,585","233,528","189,690",1.15,100,"127,500"
9,055550,신한지주,"1,145,662","241,368","3,956,803","3,639,353","474,200",0.78,"5,000","50,900"
10,032830,삼성생명,"199,162","234,000","2,646,538","2,363,454","200,000",0.79,500,"117,000"
11,105560,KB금융,"855,872","225,780","3,756,737","3,444,123","418,112",0.69,"5,000","54,000"
12,207940,삼성바이오로직스,"374,923","216,029","75,330","34,506","66,165",5.29,"2,500","326,500"
13,012330,현대모비스,"233,988","210,263","417,116","131,536","97,344",0.72,"5,000","216,000"
14,017670,SK텔레콤,"253,797","204,287","312,977","151,812","80,746",1.12,500,"253,000"
15,034730,SK,"112,509","185,048","1,030,473","607,206","70,360",1.13,200,"263,000"
16,096770,SK이노베이션,"499,883","174,760","325,813","142,763","92,466",1.03,"5,000","189,000"
17,006400,삼성SDI,"384,033","147,500","149,003","39,362","68,765",1.35,"5,000","214,500"
18,003550,LG,"410,892","146,674","194,894","52,694","172,557",1.08,"5,000","85,000"
19,066570,LG전자,"2,644,097","146,465","378,553","244,985","163,648",1.34,"5,000","89,500"
20,090430,아모레퍼시픽,"484,823","146,146","51,816","12,849","58,458",4.45,500,"250,000"
21,033780,KT&amp;G,"485,524","145,530","98,126","26,943","137,292",1.90,"5,000","106,000"
22,051900,LG생활건강,"32,048","141,969","45,022","18,813","15,618",6.01,"5,000","909,000"
23,086790,하나금융지주,"711,958","136,309","3,481,775","3,247,875","296,003",0.61,"5,000","46,050"
24,018260,삼성에스디에스,"79,064","135,024","68,420","15,509","77,378",2.63,500,"174,500"
25,011170,롯데케미칼,"300,594","132,817","158,668","64,660","34,275",1.39,"5,000","387,500"
26,010950,S-Oil,"602,361","131,159","139,590","75,674","112,583",2.12,"2,500","116,500"
27,000810,삼성화재,"67,037","128,623","682,175","572,093","47,375",1.05,500,"271,500"
28,251270,넷마블게임즈,"173,309","127,952","19,574","6,471","85,018",8.39,100,"150,500"
29,000270,기아차,"1,111,612","125,257","508,893","243,098","405,363",0.47,"5,000","30,900"
...,...,...,...,...,...,...,...,...,...,...
1324,001065,JW중외제약우,"3,641",44,N/A,N/A,161,2.06,"2,500","27,050"
1325,004835,덕성우,"7,629",43,N/A,N/A,"1,392",0.73,500,"3,100"
1326,001527,동양2우B,"1,626",43,N/A,N/A,309,3.40,500,"13,900"
1327,014285,금강공업우,364,43,N/A,N/A,118,0.63,"5,000","36,200"
1328,090355,노루페인트우,"30,396",43,N/A,N/A,463,0.68,500,"9,210"
1329,005965,동부건설우,"1,630",42,N/A,N/A,226,1.56,"5,000","18,800"
1330,000995,동부하이텍1우,310,42,N/A,N/A,112,4.77,"5,000","37,700"
1331,227560,TIGER 200 생활소비재,82,42,N/A,N/A,340,N/A,0,"12,425"
1332,004985,성신양회우,"5,320",40,N/A,N/A,736,0.43,"5,000","5,500"
1333,000325,노루홀딩스우,60,40,N/A,N/A,185,0.65,500,"21,800"
1334,016385,동부제철우,"1,904",40,N/A,N/A,160,5.03,"5,000","24,900"
1335,001067,JW중외제약2우B,"5,888",40,N/A,N/A,84,3.58,"2,500","46,900"
1336,227550,TIGER 200 산업재,325,39,N/A,N/A,660,N/A,0,"5,930"
1337,161500,ARIRANG 경기주도주,"1,426",39,N/A,N/A,600,N/A,0,"6,420"
1338,253160,ARIRANG 200선물인버스2X,"4,343",38,N/A,N/A,300,N/A,0,"12,740"
1339,002785,진흥기업우B,"8,018",38,N/A,N/A,857,-36.50,500,"4,455"
1340,000547,흥국화재2우B,"19,397",38,N/A,N/A,154,2.93,"5,000","24,800"
1341,140580,KBSTAR 우량업종,67,35,N/A,N/A,300,N/A,0,"11,585"
1342,139310,TIGER 금속선물(H),879,34,N/A,N/A,600,N/A,0,"5,735"
1343,000227,유유제약2우B,"6,583",34,N/A,N/A,164,1.90,"1,000","20,950"
1344,001799,대한제당3우B,599,34,N/A,N/A,130,0.53,"2,500","26,150"
1345,157510,TIGER 자동차,"2,064",34,N/A,N/A,260,N/A,0,"12,900"
1346,013367,일성건설2우B,"7,063",33,N/A,N/A,621,2.93,500,"5,290"
1347,008355,남선알미우,"1,728",29,N/A,N/A,308,8.46,500,"9,380"
1348,002787,진흥기업2우B,"7,239",28,N/A,N/A,295,-77.91,500,"9,510"
1349,004989,성신양회3우B,"1,340",25,N/A,N/A,287,0.67,"5,000","8,550"
1350,001529,동양3우B,"3,064",24,N/A,N/A,90,6.46,500,"26,400"
1351,161490,ARIRANG 경기방어주,132,23,N/A,N/A,300,N/A,0,"7,645"
1352,004987,성신양회2우B,"8,784",23,N/A,N/A,221,0.80,"5,000","10,200"
1353,000327,노루홀딩스2우B,0,18,N/A,N/A,93,0.58,500,"19,600"

#### ------ BREAK -----

##### Part III. Put the DF to PostgreSQL

In [32]:
# Importing relavent packages from sqlalchemy ORM
from datetime import datetime

from sqlalchemy import create_engine
from sqlalchemy import Table, Column, Integer, String, DateTime, ForeignKey
from sqlalchemy.orm import relationship, backref
from sqlalchemy.ext.declarative import declarative_base

In [33]:
db_string = "postgresql://daesik:@localhost/db_piotroski"

engine = create_engine(db_string, echo=True)

In [34]:
Base = declarative_base()

In [35]:
class Stock(Base):
    __tablename__ = 'stocks'
    
    stock_id = Column(Integer, primary_key=True)
    stock_code = Column(String, unique=True, nullable=False)
    company = Column(String, index=True, unique=True, nullable=False)
    market_type = Column(Integer)
    industry = Column(String)
    created_on = Column(DateTime, default=datetime.utcnow)
    updated_on = Column(DateTime, default=datetime.utcnow)
    
    # one-to-many & many-to-one relationship setting, if needed
    base_param = relationship("BaseParam", back_populates="stocks")
    bookmarket_param = relationship("BookMarketParam", back_populates="stocks")
    
    def __repr__(self): 
        return "<Stock --> id : {0}, code : {1}, company : {2}, market_type : {3}, created : {4}, updated : {5}>".format(self.stock_id, 
                                                                                                                         self.stock_code, 
                                                                                                                         self.company, 
                                                                                                                         self.market_type, 
                                                                                                                         self.created_on, 
                                                                                                                         self.updated_on,)

In [36]:
class BaseParam(Base): 
    __tablename__= 'base_params'
    
    baseparam_id = Column(Integer, primary_key=True)
    stock_code = Column(String, ForeignKey('stocks.stock_code'))
    date = Column(DateTime)
    price_open = Column(Integer)
    price_close = Column(Integer)
    price_high = Column(Integer)
    price_low = Column(Integer)
    quant = Column(Integer)
    market_sum = Column(Integer)
    
    # one-to-many relationship setting
    stock = relationship("Stock", back_populates="base_params")
    
    # 거래량, 향후 volume으로 변경가능. 네이버 파라미터와 맞추기 위해 quant 사용

In [37]:
class BookMarketParam(Base):
    __tablename__= 'bookmarket_params'
    
    bookmarketparam_id = Column(Integer, primary_key=True)
    stock_code = Column(String, ForeignKey('stocks.stock_code'))
    listed_stock_cnt = Column(Integer)
    property_total = Column(Integer)
    debt_total = Column(Integer)
    pbr = Column(Integer)
    
    # one-to-many relationship setting
    stock = relationship('Stock', back_populates='bookmarket_params')
    
    
    # 회사이름 및 분기 컬럼 추가??? 재무제표 관련 자료

In [38]:
Base.metadata.create_all(engine)

2017-09-17 23:18:54,386 INFO sqlalchemy.engine.base.Engine select version()
2017-09-17 23:18:54,388 INFO sqlalchemy.engine.base.Engine {}
2017-09-17 23:18:54,390 INFO sqlalchemy.engine.base.Engine select current_schema()
2017-09-17 23:18:54,392 INFO sqlalchemy.engine.base.Engine {}
2017-09-17 23:18:54,396 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2017-09-17 23:18:54,398 INFO sqlalchemy.engine.base.Engine {}
2017-09-17 23:18:54,401 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2017-09-17 23:18:54,403 INFO sqlalchemy.engine.base.Engine {}
2017-09-17 23:18:54,405 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2017-09-17 23:18:54,407 INFO sqlalchemy.engine.base.Engine {}
2017-09-17 23:18:54,411 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2017-09-17 23:18:54,414 INFO sqlalchemy.engine.base.Engine {'name': 'stocks'}
2017-09-17 23:18:54,419 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2017-09-17 23:18:54,421 INFO sqlalchemy.engine.base.Engine {'name': 'base_params'}
2017-09-17 23:18:54,424 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2017-09-17 23:18:54,426 INFO sqlalchemy.engine.base.Engine {'name': 'bookmarket_params'}
2017-09-17 23:18:54,430 INFO sqlalchemy.engine.base.Engine
CREATE TABLE base_params (
	baseparam_id SERIAL NOT NULL,
	stock_code VARCHAR,
	date TIMESTAMP WITHOUT TIME ZONE,
	price_open INTEGER,
	price_close INTEGER,
	price_high INTEGER,
	price_low INTEGER,
	quant INTEGER,
	market_sum INTEGER,
	PRIMARY KEY (baseparam_id),
	FOREIGN KEY(stock_code) REFERENCES stocks (stock_code)
)


2017-09-17 23:18:54,433 INFO sqlalchemy.engine.base.Engine {}
2017-09-17 23:18:54,446 INFO sqlalchemy.engine.base.Engine COMMIT
2017-09-17 23:18:54,451 INFO sqlalchemy.engine.base.Engine
CREATE TABLE bookmarket_params (
	bookmarketparam_id SERIAL NOT NULL,
	stock_code VARCHAR,
	listed_stock_cnt INTEGER,
	property_total INTEGER,
	debt_total INTEGER,
	pbr INTEGER,
	PRIMARY KEY (bookmarketparam_id),
	FOREIGN KEY(stock_code) REFERENCES stocks (stock_code)
)


2017-09-17 23:18:54,452 INFO sqlalchemy.engine.base.Engine {}
2017-09-17 23:18:54,461 INFO sqlalchemy.engine.base.Engine COMMIT