Implementation Plan. Part 1 - for the universe
1. things to crawl to filter or create a portfolio universe
   - 시가총액(Market Capitalization a.k.a "market cap")
   - "BV" (Book Value, Asset - Liability = SH's Equity)
   - PBR(Price-to-Book Ratio, 주가순자산비율)
   - 상장주식수

In [1]:
#Import packages
import requests 
from bs4 import BeautifulSoup

import numpy as np
import pandas as pd

In [2]:
# Crawler Building
# setting URL

url = "http://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn%3Fsosok%3D{0}%26page%3D{1}&fieldIds={2}&fieldIds={3}&fieldIds={4}&fieldIds={5}&fieldIds={6}&fieldIds={7}".format('0',
                                                                                                                                                                                                                                                             '1', 
                                                                                                                                                                                                                                                             'quant',
                                                                                                                                                                                                                                                             'listed_stock_cnt',
                                                                                                                                                                                                                                                             'market_sum',
                                                                                                                                                                                                                                                             'property_total',
                                                                                                                                                                                                                                                             'debt_total',
                                                                                                                                                                                                                                                             'pbr')
"""options to choose 
   1. 거래량 : 'quant'
   2. 시가 : 'open_val'
   3. 고가 : 'high_val'
   4. 저가 : 'loq_val' 
   5. 매수호가 : 'ask_buy'
   6. 매도호가 : 'ask_sell' 
   7. 매수총잔량 : 'buy_total'
   8. 매도총잔량 : 'sell_total'
   9. 거래대금(백만) : 'amount' 
   10. 전일거래량 : 'prev_quant'
   11. 외국인비율 : 'frgn_rate'
   12. 상장주식수(천주) : 'listed_stock_cnt'
   13. 시가총액(억) : 'market_sum'
   14. 자산총계(억) : 'property_total'
   15. 부채총계(억) : 'debt_total' 
   16. 매출액(억) : 'sales'
   17. 매출액증가율 : 'sales_increasing_rate'
   18. 영업이익(억) : 'operating_profit'
   19. 영업이익증가율 : 'operating_profit_increasing_rate' 
   20. 당기순이익(억) : 'net_income'
   21. 주당순이익(원) : 'eps'
   22. 보통주배당금(원) : 'dividend'
   23. PER(배) : 'per'
   24. ROE(%) : 'roe'
   25. ROA(%) : 'roa'
   26. PBR(배) : 'pbr'
   27. 유보율(%) : 'reserve_ratio'
   """

"options to choose \n   1. 거래량 : 'quant'\n   2. 시가 : 'open_val'\n   3. 고가 : 'high_val'\n   4. 저가 : 'loq_val' \n   5. 매수호가 : 'ask_buy'\n   6. 매도호가 : 'ask_sell' \n   7. 매수총잔량 : 'buy_total'\n   8. 매도총잔량 : 'sell_total'\n   9. 거래대금(백만) : 'amount' \n   10. 전일거래량 : 'prev_quant'\n   11. 외국인비율 : 'frgn_rate'\n   12. 상장주식수(천주) : 'listed_stock_cnt'\n   13. 시가총액(억) : 'market_sum'\n   14. 자산총계(억) : 'property_total'\n   15. 부채총계(억) : 'debt_total' \n   16. 매출액(억) : 'sales'\n   17. 매출액증가율 : 'sales_increasing_rate'\n   18. 영업이익(억) : 'operating_profit'\n   19. 영업이익증가율 : 'operating_profit_increasing_rate' \n   20. 당기순이익(억) : 'net_income'\n   21. 주당순이익(원) : 'eps'\n   22. 보통주배당금(원) : 'dividend'\n   23. PER(배) : 'per'\n   24. ROE(%) : 'roe'\n   25. ROA(%) : 'roa'\n   26. PBR(배) : 'pbr'\n   27. 유보율(%) : 'reserve_ratio'\n   "

In [3]:
# Requests
req = requests.get(url)
html = req.text

In [4]:
# BeautifulSoup - Making the soup
soup = BeautifulSoup(html, 'lxml')

In [5]:
soup.select('table.type_2 a[href]')

[<a class="tltle" href="/item/main.nhn?code=005930">삼성전자</a>,
 <a href="/item/board.nhn?code=005930"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=000660">SK하이닉스</a>,
 <a href="/item/board.nhn?code=000660"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=005935">삼성전자우</a>,
 <a href="/item/board.nhn?code=005935"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=005380">현대차</a>,
 <a href="/item/board.nhn?code=005380"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=005490">POSCO</a>,
 <a href="/item/board.nhn?code=005490"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=051910">LG화학</a>,
 <a href="/item/board.nhn?code=051910"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=035420">NAVER</a>,
 <a href="/item/board.nhn?code=035420"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=028260">삼성물산</a>,
 <a href="/item/board.nhn?code=028260"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=015760">한국전력</a>,
 <a href="/item/board.nhn?code=015760"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=055550">신한지주</a>,
 <a href="/item/board.nhn?code=055550"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=105560">KB금융</a>,
 <a href="/item/board.nhn?code=105560"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=032830">삼성생명</a>,
 <a href="/item/board.nhn?code=032830"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=207940">삼성바이오로직스</a>,
 <a href="/item/board.nhn?code=207940"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=012330">현대모비스</a>,
 <a href="/item/board.nhn?code=012330"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=017670">SK텔레콤</a>,
 <a href="/item/board.nhn?code=017670"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=034730">SK</a>,
 <a href="/item/board.nhn?code=034730"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=096770">SK이노베이션</a>,
 <a href="/item/board.nhn?code=096770"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=006400">삼성SDI</a>,
 <a href="/item/board.nhn?code=006400"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=090430">아모레퍼시픽</a>,
 <a href="/item/board.nhn?code=090430"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=033780">KT&amp;G</a>,
 <a href="/item/board.nhn?code=033780"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=066570">LG전자</a>,
 <a href="/item/board.nhn?code=066570"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=086790">하나금융지주</a>,
 <a href="/item/board.nhn?code=086790"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=003550">LG</a>,
 <a href="/item/board.nhn?code=003550"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=051900">LG생활건강</a>,
 <a href="/item/board.nhn?code=051900"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=010950">S-Oil</a>,
 <a href="/item/board.nhn?code=010950"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=251270">넷마블게임즈</a>,
 <a href="/item/board.nhn?code=251270"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=018260">삼성에스디에스</a>,
 <a href="/item/board.nhn?code=018260"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=011170">롯데케미칼</a>,
 <a href="/item/board.nhn?code=011170"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=000810">삼성화재</a>,
 <a href="/item/board.nhn?code=000810"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=000270">기아차</a>,
 <a href="/item/board.nhn?code=000270"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=000030">우리은행</a>,
 <a href="/item/board.nhn?code=000030"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=034220">LG디스플레이</a>,
 <a href="/item/board.nhn?code=034220"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=002790">아모레G</a>,
 <a href="/item/board.nhn?code=002790"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=036570">엔씨소프트</a>,
 <a href="/item/board.nhn?code=036570"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=035720">카카오</a>,
 <a href="/item/board.nhn?code=035720"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=010130">고려아연</a>,
 <a href="/item/board.nhn?code=010130"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=009540">현대중공업</a>,
 <a href="/item/board.nhn?code=009540"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=024110">기업은행</a>,
 <a href="/item/board.nhn?code=024110"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=009150">삼성전기</a>,
 <a href="/item/board.nhn?code=009150"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=030200">KT</a>,
 <a href="/item/board.nhn?code=030200"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=035250">강원랜드</a>,
 <a href="/item/board.nhn?code=035250"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=161390">한국타이어</a>,
 <a href="/item/board.nhn?code=161390"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=021240">코웨이</a>,
 <a href="/item/board.nhn?code=021240"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=004020">현대제철</a>,
 <a href="/item/board.nhn?code=004020"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=267250">현대로보틱스</a>,
 <a href="/item/board.nhn?code=267250"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=006800">미래에셋대우</a>,
 <a href="/item/board.nhn?code=006800"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=023530">롯데쇼핑</a>,
 <a href="/item/board.nhn?code=023530"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=018880">한온시스템</a>,
 <a href="/item/board.nhn?code=018880"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=009830">한화케미칼</a>,
 <a href="/item/board.nhn?code=009830"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>,
 <a class="tltle" href="/item/main.nhn?code=078930">GS</a>,
 <a href="/item/board.nhn?code=078930"><img alt="토론실" height="13" src="http://imgstock.naver.net/images5/ico_debatebl2.gif" width="15"/></a>]

In [6]:
soup.find_all('a', 'tltle')

[<a class="tltle" href="/item/main.nhn?code=005930">삼성전자</a>,
 <a class="tltle" href="/item/main.nhn?code=000660">SK하이닉스</a>,
 <a class="tltle" href="/item/main.nhn?code=005935">삼성전자우</a>,
 <a class="tltle" href="/item/main.nhn?code=005380">현대차</a>,
 <a class="tltle" href="/item/main.nhn?code=005490">POSCO</a>,
 <a class="tltle" href="/item/main.nhn?code=051910">LG화학</a>,
 <a class="tltle" href="/item/main.nhn?code=035420">NAVER</a>,
 <a class="tltle" href="/item/main.nhn?code=028260">삼성물산</a>,
 <a class="tltle" href="/item/main.nhn?code=015760">한국전력</a>,
 <a class="tltle" href="/item/main.nhn?code=055550">신한지주</a>,
 <a class="tltle" href="/item/main.nhn?code=105560">KB금융</a>,
 <a class="tltle" href="/item/main.nhn?code=032830">삼성생명</a>,
 <a class="tltle" href="/item/main.nhn?code=207940">삼성바이오로직스</a>,
 <a class="tltle" href="/item/main.nhn?code=012330">현대모비스</a>,
 <a class="tltle" href="/item/main.nhn?code=017670">SK텔레콤</a>,
 <a class="tltle" href="/item/main.nhn?code=034730">SK</a>,
 <a class="tltle" href="/item/main.nhn?code=096770">SK이노베이션</a>,
 <a class="tltle" href="/item/main.nhn?code=006400">삼성SDI</a>,
 <a class="tltle" href="/item/main.nhn?code=090430">아모레퍼시픽</a>,
 <a class="tltle" href="/item/main.nhn?code=033780">KT&amp;G</a>,
 <a class="tltle" href="/item/main.nhn?code=066570">LG전자</a>,
 <a class="tltle" href="/item/main.nhn?code=086790">하나금융지주</a>,
 <a class="tltle" href="/item/main.nhn?code=003550">LG</a>,
 <a class="tltle" href="/item/main.nhn?code=051900">LG생활건강</a>,
 <a class="tltle" href="/item/main.nhn?code=010950">S-Oil</a>,
 <a class="tltle" href="/item/main.nhn?code=251270">넷마블게임즈</a>,
 <a class="tltle" href="/item/main.nhn?code=018260">삼성에스디에스</a>,
 <a class="tltle" href="/item/main.nhn?code=011170">롯데케미칼</a>,
 <a class="tltle" href="/item/main.nhn?code=000810">삼성화재</a>,
 <a class="tltle" href="/item/main.nhn?code=000270">기아차</a>,
 <a class="tltle" href="/item/main.nhn?code=000030">우리은행</a>,
 <a class="tltle" href="/item/main.nhn?code=034220">LG디스플레이</a>,
 <a class="tltle" href="/item/main.nhn?code=002790">아모레G</a>,
 <a class="tltle" href="/item/main.nhn?code=036570">엔씨소프트</a>,
 <a class="tltle" href="/item/main.nhn?code=035720">카카오</a>,
 <a class="tltle" href="/item/main.nhn?code=010130">고려아연</a>,
 <a class="tltle" href="/item/main.nhn?code=009540">현대중공업</a>,
 <a class="tltle" href="/item/main.nhn?code=024110">기업은행</a>,
 <a class="tltle" href="/item/main.nhn?code=009150">삼성전기</a>,
 <a class="tltle" href="/item/main.nhn?code=030200">KT</a>,
 <a class="tltle" href="/item/main.nhn?code=035250">강원랜드</a>,
 <a class="tltle" href="/item/main.nhn?code=161390">한국타이어</a>,
 <a class="tltle" href="/item/main.nhn?code=021240">코웨이</a>,
 <a class="tltle" href="/item/main.nhn?code=004020">현대제철</a>,
 <a class="tltle" href="/item/main.nhn?code=267250">현대로보틱스</a>,
 <a class="tltle" href="/item/main.nhn?code=006800">미래에셋대우</a>,
 <a class="tltle" href="/item/main.nhn?code=023530">롯데쇼핑</a>,
 <a class="tltle" href="/item/main.nhn?code=018880">한온시스템</a>,
 <a class="tltle" href="/item/main.nhn?code=009830">한화케미칼</a>,
 <a class="tltle" href="/item/main.nhn?code=078930">GS</a>]

In [7]:
import re
soup.find_all(href = re.compile("/item/main.nhn?"))

[<a class="tltle" href="/item/main.nhn?code=005930">삼성전자</a>,
 <a class="tltle" href="/item/main.nhn?code=000660">SK하이닉스</a>,
 <a class="tltle" href="/item/main.nhn?code=005935">삼성전자우</a>,
 <a class="tltle" href="/item/main.nhn?code=005380">현대차</a>,
 <a class="tltle" href="/item/main.nhn?code=005490">POSCO</a>,
 <a class="tltle" href="/item/main.nhn?code=051910">LG화학</a>,
 <a class="tltle" href="/item/main.nhn?code=035420">NAVER</a>,
 <a class="tltle" href="/item/main.nhn?code=028260">삼성물산</a>,
 <a class="tltle" href="/item/main.nhn?code=015760">한국전력</a>,
 <a class="tltle" href="/item/main.nhn?code=055550">신한지주</a>,
 <a class="tltle" href="/item/main.nhn?code=105560">KB금융</a>,
 <a class="tltle" href="/item/main.nhn?code=032830">삼성생명</a>,
 <a class="tltle" href="/item/main.nhn?code=207940">삼성바이오로직스</a>,
 <a class="tltle" href="/item/main.nhn?code=012330">현대모비스</a>,
 <a class="tltle" href="/item/main.nhn?code=017670">SK텔레콤</a>,
 <a class="tltle" href="/item/main.nhn?code=034730">SK</a>,
 <a class="tltle" href="/item/main.nhn?code=096770">SK이노베이션</a>,
 <a class="tltle" href="/item/main.nhn?code=006400">삼성SDI</a>,
 <a class="tltle" href="/item/main.nhn?code=090430">아모레퍼시픽</a>,
 <a class="tltle" href="/item/main.nhn?code=033780">KT&amp;G</a>,
 <a class="tltle" href="/item/main.nhn?code=066570">LG전자</a>,
 <a class="tltle" href="/item/main.nhn?code=086790">하나금융지주</a>,
 <a class="tltle" href="/item/main.nhn?code=003550">LG</a>,
 <a class="tltle" href="/item/main.nhn?code=051900">LG생활건강</a>,
 <a class="tltle" href="/item/main.nhn?code=010950">S-Oil</a>,
 <a class="tltle" href="/item/main.nhn?code=251270">넷마블게임즈</a>,
 <a class="tltle" href="/item/main.nhn?code=018260">삼성에스디에스</a>,
 <a class="tltle" href="/item/main.nhn?code=011170">롯데케미칼</a>,
 <a class="tltle" href="/item/main.nhn?code=000810">삼성화재</a>,
 <a class="tltle" href="/item/main.nhn?code=000270">기아차</a>,
 <a class="tltle" href="/item/main.nhn?code=000030">우리은행</a>,
 <a class="tltle" href="/item/main.nhn?code=034220">LG디스플레이</a>,
 <a class="tltle" href="/item/main.nhn?code=002790">아모레G</a>,
 <a class="tltle" href="/item/main.nhn?code=036570">엔씨소프트</a>,
 <a class="tltle" href="/item/main.nhn?code=035720">카카오</a>,
 <a class="tltle" href="/item/main.nhn?code=010130">고려아연</a>,
 <a class="tltle" href="/item/main.nhn?code=009540">현대중공업</a>,
 <a class="tltle" href="/item/main.nhn?code=024110">기업은행</a>,
 <a class="tltle" href="/item/main.nhn?code=009150">삼성전기</a>,
 <a class="tltle" href="/item/main.nhn?code=030200">KT</a>,
 <a class="tltle" href="/item/main.nhn?code=035250">강원랜드</a>,
 <a class="tltle" href="/item/main.nhn?code=161390">한국타이어</a>,
 <a class="tltle" href="/item/main.nhn?code=021240">코웨이</a>,
 <a class="tltle" href="/item/main.nhn?code=004020">현대제철</a>,
 <a class="tltle" href="/item/main.nhn?code=267250">현대로보틱스</a>,
 <a class="tltle" href="/item/main.nhn?code=006800">미래에셋대우</a>,
 <a class="tltle" href="/item/main.nhn?code=023530">롯데쇼핑</a>,
 <a class="tltle" href="/item/main.nhn?code=018880">한온시스템</a>,
 <a class="tltle" href="/item/main.nhn?code=009830">한화케미칼</a>,
 <a class="tltle" href="/item/main.nhn?code=078930">GS</a>]

In [8]:
a = '<a class="tltle" href="/item/main.nhn?code=000030">우리은행</a>'
a.strip('"<>/a').split('=')[-1].split('">')

['000030', '우리은행']

In [9]:
soup.select('a[href*="/item/main.nhn"], td[class^="number"]')

[<a class="tltle" href="/item/main.nhn?code=005930">삼성전자</a>,
 <a class="tltle" href="/item/main.nhn?code=000660">SK하이닉스</a>,
 <a class="tltle" href="/item/main.nhn?code=005935">삼성전자우</a>,
 <a class="tltle" href="/item/main.nhn?code=005380">현대차</a>,
 <a class="tltle" href="/item/main.nhn?code=005490">POSCO</a>,
 <a class="tltle" href="/item/main.nhn?code=051910">LG화학</a>,
 <a class="tltle" href="/item/main.nhn?code=035420">NAVER</a>,
 <a class="tltle" href="/item/main.nhn?code=028260">삼성물산</a>,
 <a class="tltle" href="/item/main.nhn?code=015760">한국전력</a>,
 <a class="tltle" href="/item/main.nhn?code=055550">신한지주</a>,
 <a class="tltle" href="/item/main.nhn?code=105560">KB금융</a>,
 <a class="tltle" href="/item/main.nhn?code=032830">삼성생명</a>,
 <a class="tltle" href="/item/main.nhn?code=207940">삼성바이오로직스</a>,
 <a class="tltle" href="/item/main.nhn?code=012330">현대모비스</a>,
 <a class="tltle" href="/item/main.nhn?code=017670">SK텔레콤</a>,
 <a class="tltle" href="/item/main.nhn?code=034730">SK</a>,
 <a class="tltle" href="/item/main.nhn?code=096770">SK이노베이션</a>,
 <a class="tltle" href="/item/main.nhn?code=006400">삼성SDI</a>,
 <a class="tltle" href="/item/main.nhn?code=090430">아모레퍼시픽</a>,
 <a class="tltle" href="/item/main.nhn?code=033780">KT&amp;G</a>,
 <a class="tltle" href="/item/main.nhn?code=066570">LG전자</a>,
 <a class="tltle" href="/item/main.nhn?code=086790">하나금융지주</a>,
 <a class="tltle" href="/item/main.nhn?code=003550">LG</a>,
 <a class="tltle" href="/item/main.nhn?code=051900">LG생활건강</a>,
 <a class="tltle" href="/item/main.nhn?code=010950">S-Oil</a>,
 <a class="tltle" href="/item/main.nhn?code=251270">넷마블게임즈</a>,
 <a class="tltle" href="/item/main.nhn?code=018260">삼성에스디에스</a>,
 <a class="tltle" href="/item/main.nhn?code=011170">롯데케미칼</a>,
 <a class="tltle" href="/item/main.nhn?code=000810">삼성화재</a>,
 <a class="tltle" href="/item/main.nhn?code=000270">기아차</a>,
 <a class="tltle" href="/item/main.nhn?code=000030">우리은행</a>,
 <a class="tltle" href="/item/main.nhn?code=034220">LG디스플레이</a>,
 <a class="tltle" href="/item/main.nhn?code=002790">아모레G</a>,
 <a class="tltle" href="/item/main.nhn?code=036570">엔씨소프트</a>,
 <a class="tltle" href="/item/main.nhn?code=035720">카카오</a>,
 <a class="tltle" href="/item/main.nhn?code=010130">고려아연</a>,
 <a class="tltle" href="/item/main.nhn?code=009540">현대중공업</a>,
 <a class="tltle" href="/item/main.nhn?code=024110">기업은행</a>,
 <a class="tltle" href="/item/main.nhn?code=009150">삼성전기</a>,
 <a class="tltle" href="/item/main.nhn?code=030200">KT</a>,
 <a class="tltle" href="/item/main.nhn?code=035250">강원랜드</a>,
 <a class="tltle" href="/item/main.nhn?code=161390">한국타이어</a>,
 <a class="tltle" href="/item/main.nhn?code=021240">코웨이</a>,
 <a class="tltle" href="/item/main.nhn?code=004020">현대제철</a>,
 <a class="tltle" href="/item/main.nhn?code=267250">현대로보틱스</a>,
 <a class="tltle" href="/item/main.nhn?code=006800">미래에셋대우</a>,
 <a class="tltle" href="/item/main.nhn?code=023530">롯데쇼핑</a>,
 <a class="tltle" href="/item/main.nhn?code=018880">한온시스템</a>,
 <a class="tltle" href="/item/main.nhn?code=009830">한화케미칼</a>,
 <a class="tltle" href="/item/main.nhn?code=078930">GS</a>,
 <td class="number">2,611,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				5,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.19%
 				</span>
 </td>,
 <td class="number">5,000</td>,
 <td class="number">182,388</td>,
 <td class="number">129,768</td>,
 <td class="number">3,388,255</td>,
 <td class="number">2,621,743</td>,
 <td class="number">692,113</td>,
 <td class="number">1.96</td>,
 <td class="number">80,700</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,500
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.89%
 				</span>
 </td>,
 <td class="number">5,250,342</td>,
 <td class="number">728,002</td>,
 <td class="number">587,498</td>,
 <td class="number">322,160</td>,
 <td class="number">81,925</td>,
 <td class="number">2.37</td>,
 <td class="number">2,125,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				10,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.47%
 				</span>
 </td>,
 <td class="number">27,837</td>,
 <td class="number">18,419</td>,
 <td class="number">391,395</td>,
 <td class="number">N/A</td>,
 <td class="number">1.60</td>,
 <td class="number">142,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				2,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.43%
 				</span>
 </td>,
 <td class="number">618,302</td>,
 <td class="number">220,276</td>,
 <td class="number">312,793</td>,
 <td class="number">1,788,359</td>,
 <td class="number">1,064,914</td>,
 <td class="number">0.57</td>,
 <td class="number">325,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.31%
 				</span>
 </td>,
 <td class="number">176,351</td>,
 <td class="number">87,187</td>,
 <td class="number">283,357</td>,
 <td class="number">797,630</td>,
 <td class="number">339,246</td>,
 <td class="number">0.61</td>,
 <td class="number">388,500</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				8,500
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-2.14%
 				</span>
 </td>,
 <td class="number">323,605</td>,
 <td class="number">70,592</td>,
 <td class="number">274,251</td>,
 <td class="number">204,871</td>,
 <td class="number">64,361</td>,
 <td class="number">2.01</td>,
 <td class="number">783,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				13,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.69%
 				</span>
 </td>,
 <td class="number">500</td>,
 <td class="number">86,265</td>,
 <td class="number">32,963</td>,
 <td class="number">258,098</td>,
 <td class="number">63,706</td>,
 <td class="number">22,410</td>,
 <td class="number">6.27</td>,
 <td class="number">134,000</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				1,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.74%
 				</span>
 </td>,
 <td class="number">100</td>,
 <td class="number">397,429</td>,
 <td class="number">189,690</td>,
 <td class="number">254,185</td>,
 <td class="number">444,585</td>,
 <td class="number">233,528</td>,
 <td class="number">1.21</td>,
 <td class="number">39,350</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				800
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-1.99%
 				</span>
 </td>,
 <td class="number">2,053,710</td>,
 <td class="number">641,964</td>,
 <td class="number">252,613</td>,
 <td class="number">1,778,370</td>,
 <td class="number">1,047,865</td>,
 <td class="number">0.35</td>,
 <td class="number">51,300</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				100
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.20%
 				</span>
 </td>,
 <td class="number">793,866</td>,
 <td class="number">474,200</td>,
 <td class="number">243,264</td>,
 <td class="number">3,956,803</td>,
 <td class="number">3,639,353</td>,
 <td class="number">0.78</td>,
 <td class="number">55,600</td>,
 <td class="number">
 <span class="tah p11">0</span>
 </td>,
 <td class="number">
 <span class="tah p11">0.00%</span>
 </td>,
 <td class="number">969,348</td>,
 <td class="number">418,112</td>,
 <td class="number">232,470</td>,
 <td class="number">3,756,737</td>,
 <td class="number">3,444,123</td>,
 <td class="number">0.71</td>,
 <td class="number">114,500</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				1,500
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-1.29%
 				</span>
 </td>,
 <td class="number">200,918</td>,
 <td class="number">200,000</td>,
 <td class="number">229,000</td>,
 <td class="number">2,646,538</td>,
 <td class="number">2,363,454</td>,
 <td class="number">0.77</td>,
 <td class="number">338,000</td>,
 <td class="number">2,500</td>,
 <td class="number">324,132</td>,
 <td class="number">66,165</td>,
 <td class="number">223,638</td>,
 <td class="number">75,330</td>,
 <td class="number">34,506</td>,
 <td class="number">5.48</td>,
 <td class="number">219,000</td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.69%
 				</span>
 </td>,
 <td class="number">301,793</td>,
 <td class="number">97,344</td>,
 <td class="number">213,183</td>,
 <td class="number">417,116</td>,
 <td class="number">131,536</td>,
 <td class="number">0.73</td>,
 <td class="number">245,500</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				500
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.20%
 				</span>
 </td>,
 <td class="number">133,610</td>,
 <td class="number">80,746</td>,
 <td class="number">198,231</td>,
 <td class="number">312,977</td>,
 <td class="number">151,812</td>,
 <td class="number">1.09</td>,
 <td class="number">270,500</td>,
 <td class="number">200</td>,
 <td class="number">90,304</td>,
 <td class="number">70,360</td>,
 <td class="number">190,325</td>,
 <td class="number">1,030,473</td>,
 <td class="number">607,206</td>,
 <td class="number">1.16</td>,
 <td class="number">191,000</td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.79%
 				</span>
 </td>,
 <td class="number">219,277</td>,
 <td class="number">92,466</td>,
 <td class="number">176,609</td>,
 <td class="number">325,813</td>,
 <td class="number">142,763</td>,
 <td class="number">1.04</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				4,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-1.79%
 				</span>
 </td>,
 <td class="number">333,856</td>,
 <td class="number">68,765</td>,
 <td class="number">150,594</td>,
 <td class="number">149,003</td>,
 <td class="number">39,362</td>,
 <td class="number">1.38</td>,
 <td class="number">251,000</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				2,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.79%
 				</span>
 </td>,
 <td class="number">166,797</td>,
 <td class="number">58,458</td>,
 <td class="number">146,731</td>,
 <td class="number">51,816</td>,
 <td class="number">12,849</td>,
 <td class="number">4.46</td>,
 <td class="number">104,500</td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.46%
 				</span>
 </td>,
 <td class="number">280,184</td>,
 <td class="number">137,292</td>,
 <td class="number">143,471</td>,
 <td class="number">98,126</td>,
 <td class="number">26,943</td>,
 <td class="number">1.87</td>,
 <td class="number">86,600</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				2,400
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-2.70%
 				</span>
 </td>,
 <td class="number">1,662,554</td>,
 <td class="number">163,648</td>,
 <td class="number">141,719</td>,
 <td class="number">378,553</td>,
 <td class="number">244,985</td>,
 <td class="number">1.30</td>,
 <td class="number">47,650</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				200
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.42%
 				</span>
 </td>,
 <td class="number">627,900</td>,
 <td class="number">296,003</td>,
 <td class="number">141,045</td>,
 <td class="number">3,481,775</td>,
 <td class="number">3,247,875</td>,
 <td class="number">0.63</td>,
 <td class="number">81,400</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				1,900
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-2.28%
 				</span>
 </td>,
 <td class="number">270,383</td>,
 <td class="number">172,557</td>,
 <td class="number">140,462</td>,
 <td class="number">194,894</td>,
 <td class="number">52,694</td>,
 <td class="number">1.03</td>,
 <td class="number">898,000</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				20,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-2.18%
 				</span>
 </td>,
 <td class="number">22,501</td>,
 <td class="number">15,618</td>,
 <td class="number">140,251</td>,
 <td class="number">45,022</td>,
 <td class="number">18,813</td>,
 <td class="number">5.94</td>,
 <td class="number">120,000</td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.41%
 				</span>
 </td>,
 <td class="number">214,217</td>,
 <td class="number">112,583</td>,
 <td class="number">135,099</td>,
 <td class="number">139,590</td>,
 <td class="number">75,674</td>,
 <td class="number">2.19</td>,
 <td class="number">156,500</td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.29%
 				</span>
 </td>,
 <td class="number">255,918</td>,
 <td class="number">85,018</td>,
 <td class="number">133,054</td>,
 <td class="number">19,574</td>,
 <td class="number">6,471</td>,
 <td class="number">8.72</td>,
 <td class="number">171,500</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				3,500
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-2.00%
 				</span>
 </td>,
 <td class="number">95,700</td>,
 <td class="number">77,378</td>,
 <td class="number">132,703</td>,
 <td class="number">68,420</td>,
 <td class="number">15,509</td>,
 <td class="number">2.58</td>,
 <td class="number">381,000</td>,
 <td class="number">105,912</td>,
 <td class="number">34,275</td>,
 <td class="number">130,589</td>,
 <td class="number">158,668</td>,
 <td class="number">64,660</td>,
 <td class="number">1.37</td>,
 <td class="number">273,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				4,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.49%
 				</span>
 </td>,
 <td class="number">63,253</td>,
 <td class="number">47,375</td>,
 <td class="number">129,333</td>,
 <td class="number">682,175</td>,
 <td class="number">572,093</td>,
 <td class="number">1.06</td>,
 <td class="number">31,350</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				350
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.13%
 				</span>
 </td>,
 <td class="number">1,081,249</td>,
 <td class="number">405,363</td>,
 <td class="number">127,081</td>,
 <td class="number">508,893</td>,
 <td class="number">243,098</td>,
 <td class="number">0.47</td>,
 <td class="number">18,050</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				150
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.84%
 				</span>
 </td>,
 <td class="number">1,027,967</td>,
 <td class="number">676,000</td>,
 <td class="number">122,018</td>,
 <td class="number">3,106,827</td>,
 <td class="number">2,901,368</td>,
 <td class="number">0.60</td>,
 <td class="number">31,550</td>,
 <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				750
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-2.32%
 				</span>
 </td>,
 <td class="number">5,590,720</td>,
 <td class="number">357,816</td>,
 <td class="number">112,891</td>,
 <td class="number">248,843</td>,
 <td class="number">114,219</td>,
 <td class="number">0.87</td>,
 <td class="number">125,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				3,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+2.46%
 				</span>
 </td>,
 <td class="number">184,950</td>,
 <td class="number">82,458</td>,
 <td class="number">103,073</td>,
 <td class="number">70,884</td>,
 <td class="number">15,215</td>,
 <td class="number">3.67</td>,
 <td class="number">467,000</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				8,500
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.85%
 				</span>
 </td>,
 <td class="number">178,339</td>,
 <td class="number">21,939</td>,
 <td class="number">102,455</td>,
 <td class="number">23,608</td>,
 <td class="number">4,653</td>,
 <td class="number">5.26</td>,
 <td class="number">142,500</td>,
 <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				5,500
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+4.01%
 				</span>
 </td>,
 <td class="number">1,307,551</td>,
 <td class="number">67,793</td>,
 <td class="number">96,605</td>,
 <td class="number">54,841</td>,
 <td class="number">17,812</td>,
 <td class="number">2.81</td>,
 <td class="number">502,000</td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.40%
 				</span>
 </td>,
 <td class="number">31,652</td>,
 <td class="number">18,870</td>,
 <td class="number">94,727</td>,
 <td class="number">64,826</td>,
 <td class="number">8,199</td>,
 <td class="number">1.61</td>,
 <td class="number">146,500</td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-1.35%
 				</span>
 </td>,
 <td class="number">130,424</td>,
 <td class="number">56,665</td>,
 <td class="number">83,015</td>,
 <td class="number">492,492</td>,

In [10]:
# Making a dict to contain all values for Piotroski Universe - To identify Book-to-Market Value and small-to-medium firm
from collections import defaultdict

piotroski_size = defaultdict(list)

In [11]:
stock_ids = soup.select('a[href*="/item/main.nhn"]')

In [12]:
stock_ids

[<a class="tltle" href="/item/main.nhn?code=005930">삼성전자</a>,
 <a class="tltle" href="/item/main.nhn?code=000660">SK하이닉스</a>,
 <a class="tltle" href="/item/main.nhn?code=005935">삼성전자우</a>,
 <a class="tltle" href="/item/main.nhn?code=005380">현대차</a>,
 <a class="tltle" href="/item/main.nhn?code=005490">POSCO</a>,
 <a class="tltle" href="/item/main.nhn?code=051910">LG화학</a>,
 <a class="tltle" href="/item/main.nhn?code=035420">NAVER</a>,
 <a class="tltle" href="/item/main.nhn?code=028260">삼성물산</a>,
 <a class="tltle" href="/item/main.nhn?code=015760">한국전력</a>,
 <a class="tltle" href="/item/main.nhn?code=055550">신한지주</a>,
 <a class="tltle" href="/item/main.nhn?code=105560">KB금융</a>,
 <a class="tltle" href="/item/main.nhn?code=032830">삼성생명</a>,
 <a class="tltle" href="/item/main.nhn?code=207940">삼성바이오로직스</a>,
 <a class="tltle" href="/item/main.nhn?code=012330">현대모비스</a>,
 <a class="tltle" href="/item/main.nhn?code=017670">SK텔레콤</a>,
 <a class="tltle" href="/item/main.nhn?code=034730">SK</a>,
 <a class="tltle" href="/item/main.nhn?code=096770">SK이노베이션</a>,
 <a class="tltle" href="/item/main.nhn?code=006400">삼성SDI</a>,
 <a class="tltle" href="/item/main.nhn?code=090430">아모레퍼시픽</a>,
 <a class="tltle" href="/item/main.nhn?code=033780">KT&amp;G</a>,
 <a class="tltle" href="/item/main.nhn?code=066570">LG전자</a>,
 <a class="tltle" href="/item/main.nhn?code=086790">하나금융지주</a>,
 <a class="tltle" href="/item/main.nhn?code=003550">LG</a>,
 <a class="tltle" href="/item/main.nhn?code=051900">LG생활건강</a>,
 <a class="tltle" href="/item/main.nhn?code=010950">S-Oil</a>,
 <a class="tltle" href="/item/main.nhn?code=251270">넷마블게임즈</a>,
 <a class="tltle" href="/item/main.nhn?code=018260">삼성에스디에스</a>,
 <a class="tltle" href="/item/main.nhn?code=011170">롯데케미칼</a>,
 <a class="tltle" href="/item/main.nhn?code=000810">삼성화재</a>,
 <a class="tltle" href="/item/main.nhn?code=000270">기아차</a>,
 <a class="tltle" href="/item/main.nhn?code=000030">우리은행</a>,
 <a class="tltle" href="/item/main.nhn?code=034220">LG디스플레이</a>,
 <a class="tltle" href="/item/main.nhn?code=002790">아모레G</a>,
 <a class="tltle" href="/item/main.nhn?code=036570">엔씨소프트</a>,
 <a class="tltle" href="/item/main.nhn?code=035720">카카오</a>,
 <a class="tltle" href="/item/main.nhn?code=010130">고려아연</a>,
 <a class="tltle" href="/item/main.nhn?code=009540">현대중공업</a>,
 <a class="tltle" href="/item/main.nhn?code=024110">기업은행</a>,
 <a class="tltle" href="/item/main.nhn?code=009150">삼성전기</a>,
 <a class="tltle" href="/item/main.nhn?code=030200">KT</a>,
 <a class="tltle" href="/item/main.nhn?code=035250">강원랜드</a>,
 <a class="tltle" href="/item/main.nhn?code=161390">한국타이어</a>,
 <a class="tltle" href="/item/main.nhn?code=021240">코웨이</a>,
 <a class="tltle" href="/item/main.nhn?code=004020">현대제철</a>,
 <a class="tltle" href="/item/main.nhn?code=267250">현대로보틱스</a>,
 <a class="tltle" href="/item/main.nhn?code=006800">미래에셋대우</a>,
 <a class="tltle" href="/item/main.nhn?code=023530">롯데쇼핑</a>,
 <a class="tltle" href="/item/main.nhn?code=018880">한온시스템</a>,
 <a class="tltle" href="/item/main.nhn?code=009830">한화케미칼</a>,
 <a class="tltle" href="/item/main.nhn?code=078930">GS</a>]

In [13]:
stock_id_ls = []
stock_name_ls = [] 
for id in stock_ids: 
    stock_id_ls.append(str(id).strip('"<>/a').split('=')[-1].split('">')[0])
    stock_name_ls.append(str(id).strip('"<>/a').split('=')[-1].split('">')[1])

In [14]:
len(stock_id_ls)

50

In [15]:
len(stock_name_ls)

50

In [16]:
# Convert stock ids & names lists to Pandas DF 
df_piotroski = pd.DataFrame({'id' : stock_id_ls, 'name': stock_name_ls}, columns = ['id', 'name', 'market_type', 'quant', 'market_sum', 'property_total', 'debt_total', 'listed_stock_cnt', 'pbr', 'face_value',])

In [17]:
df_piotroski['market_type'] = 1
# KOSPI '1' , KOSDAQ '2'

In [18]:
df_piotroski

,id,name,market_type,quant,market_sum,property_total,debt_total,listed_stock_cnt,pbr,face_value
0,005930,삼성전자,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,000660,SK하이닉스,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,005935,삼성전자우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,005380,현대차,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,005490,POSCO,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,051910,LG화학,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,035420,NAVER,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,028260,삼성물산,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,015760,한국전력,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,055550,신한지주,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,105560,KB금융,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,032830,삼성생명,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,207940,삼성바이오로직스,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,012330,현대모비스,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,017670,SK텔레콤,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,034730,SK,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,096770,SK이노베이션,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,006400,삼성SDI,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,090430,아모레퍼시픽,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,033780,KT&amp;G,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,066570,LG전자,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,086790,하나금융지주,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,003550,LG,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,051900,LG생활건강,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,010950,S-Oil,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,251270,넷마블게임즈,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,018260,삼성에스디에스,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,011170,롯데케미칼,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,000810,삼성화재,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,000270,기아차,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,000030,우리은행,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,034220,LG디스플레이,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,002790,아모레G,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,036570,엔씨소프트,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,035720,카카오,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,010130,고려아연,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,009540,현대중공업,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,024110,기업은행,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,009150,삼성전기,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,030200,KT,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,035250,강원랜드,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,161390,한국타이어,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,021240,코웨이,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,004020,현대제철,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,267250,현대로보틱스,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,006800,미래에셋대우,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,023530,롯데쇼핑,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,018880,한온시스템,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,009830,한화케미칼,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,078930,GS,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
piotroski_univ_sets = soup.select('td[class^="number"]')
piotroski_univ_sets

[<td class="number">2,611,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				5,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.19%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">182,388</td>, <td class="number">129,768</td>, <td class="number">3,388,255</td>, <td class="number">2,621,743</td>, <td class="number">692,113</td>, <td class="number">1.96</td>, <td class="number">80,700</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.89%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">5,250,342</td>, <td class="number">728,002</td>, <td class="number">587,498</td>, <td class="number">322,160</td>, <td class="number">81,925</td>, <td class="number">2.37</td>, <td class="number">2,125,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				10,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.47%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">27,837</td>, <td class="number">18,419</td>, <td class="number">391,395</td>, <td class="number">N/A</td>, <td class="number">N/A</td>, <td class="number">1.60</td>, <td class="number">142,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				2,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.43%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">618,302</td>, <td class="number">220,276</td>, <td class="number">312,793</td>, <td class="number">1,788,359</td>, <td class="number">1,064,914</td>, <td class="number">0.57</td>, <td class="number">325,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.31%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">176,351</td>, <td class="number">87,187</td>, <td class="number">283,357</td>, <td class="number">797,630</td>, <td class="number">339,246</td>, <td class="number">0.61</td>, <td class="number">388,500</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				8,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-2.14%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">323,605</td>, <td class="number">70,592</td>, <td class="number">274,251</td>, <td class="number">204,871</td>, <td class="number">64,361</td>, <td class="number">2.01</td>, <td class="number">783,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				13,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.69%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">86,265</td>, <td class="number">32,963</td>, <td class="number">258,098</td>, <td class="number">63,706</td>, <td class="number">22,410</td>, <td class="number">6.27</td>, <td class="number">134,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				1,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-0.74%
 				</span>
 </td>, <td class="number">100</td>, <td class="number">397,429</td>, <td class="number">189,690</td>, <td class="number">254,185</td>, <td class="number">444,585</td>, <td class="number">233,528</td>, <td class="number">1.21</td>, <td class="number">39,350</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				800
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-1.99%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">2,053,710</td>, <td class="number">641,964</td>, <td class="number">252,613</td>, <td class="number">1,778,370</td>, <td class="number">1,047,865</td>, <td class="number">0.35</td>, <td class="number">51,300</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				100
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.20%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">793,866</td>, <td class="number">474,200</td>, <td class="number">243,264</td>, <td class="number">3,956,803</td>, <td class="number">3,639,353</td>, <td class="number">0.78</td>, <td class="number">55,600</td>, <td class="number">
 <span class="tah p11">0</span>
 </td>, <td class="number">
 <span class="tah p11">0.00%</span>
 </td>, <td class="number">5,000</td>, <td class="number">969,348</td>, <td class="number">418,112</td>, <td class="number">232,470</td>, <td class="number">3,756,737</td>, <td class="number">3,444,123</td>, <td class="number">0.71</td>, <td class="number">114,500</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				1,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-1.29%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">200,918</td>, <td class="number">200,000</td>, <td class="number">229,000</td>, <td class="number">2,646,538</td>, <td class="number">2,363,454</td>, <td class="number">0.77</td>, <td class="number">338,000</td>, <td class="number">
 <span class="tah p11">0</span>
 </td>, <td class="number">
 <span class="tah p11">0.00%</span>
 </td>, <td class="number">2,500</td>, <td class="number">324,132</td>, <td class="number">66,165</td>, <td class="number">223,638</td>, <td class="number">75,330</td>, <td class="number">34,506</td>, <td class="number">5.48</td>, <td class="number">219,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.69%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">301,793</td>, <td class="number">97,344</td>, <td class="number">213,183</td>, <td class="number">417,116</td>, <td class="number">131,536</td>, <td class="number">0.73</td>, <td class="number">245,500</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-0.20%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">133,610</td>, <td class="number">80,746</td>, <td class="number">198,231</td>, <td class="number">312,977</td>, <td class="number">151,812</td>, <td class="number">1.09</td>, <td class="number">270,500</td>, <td class="number">
 <span class="tah p11">0</span>
 </td>, <td class="number">
 <span class="tah p11">0.00%</span>
 </td>, <td class="number">200</td>, <td class="number">90,304</td>, <td class="number">70,360</td>, <td class="number">190,325</td>, <td class="number">1,030,473</td>, <td class="number">607,206</td>, <td class="number">1.16</td>, <td class="number">191,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.79%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">219,277</td>, <td class="number">92,466</td>, <td class="number">176,609</td>, <td class="number">325,813</td>, <td class="number">142,763</td>, <td class="number">1.04</td>, <td class="number">219,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				4,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-1.79%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">333,856</td>, <td class="number">68,765</td>, <td class="number">150,594</td>, <td class="number">149,003</td>, <td class="number">39,362</td>, <td class="number">1.38</td>, <td class="number">251,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				2,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-0.79%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">166,797</td>, <td class="number">58,458</td>, <td class="number">146,731</td>, <td class="number">51,816</td>, <td class="number">12,849</td>, <td class="number">4.46</td>, <td class="number">104,500</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				1,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.46%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">280,184</td>, <td class="number">137,292</td>, <td class="number">143,471</td>, <td class="number">98,126</td>, <td class="number">26,943</td>, <td class="number">1.87</td>, <td class="number">86,600</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				2,400
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-2.70%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">1,662,554</td>, <td class="number">163,648</td>, <td class="number">141,719</td>, <td class="number">378,553</td>, <td class="number">244,985</td>, <td class="number">1.30</td>, <td class="number">47,650</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				200
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.42%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">627,900</td>, <td class="number">296,003</td>, <td class="number">141,045</td>, <td class="number">3,481,775</td>, <td class="number">3,247,875</td>, <td class="number">0.63</td>, <td class="number">81,400</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				1,900
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-2.28%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">270,383</td>, <td class="number">172,557</td>, <td class="number">140,462</td>, <td class="number">194,894</td>, <td class="number">52,694</td>, <td class="number">1.03</td>, <td class="number">898,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				20,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-2.18%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">22,501</td>, <td class="number">15,618</td>, <td class="number">140,251</td>, <td class="number">45,022</td>, <td class="number">18,813</td>, <td class="number">5.94</td>, <td class="number">120,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-0.41%
 				</span>
 </td>, <td class="number">2,500</td>, <td class="number">214,217</td>, <td class="number">112,583</td>, <td class="number">135,099</td>, <td class="number">139,590</td>, <td class="number">75,674</td>, <td class="number">2.19</td>, <td class="number">156,500</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				2,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.29%
 				</span>
 </td>, <td class="number">100</td>, <td class="number">255,918</td>, <td class="number">85,018</td>, <td class="number">133,054</td>, <td class="number">19,574</td>, <td class="number">6,471</td>, <td class="number">8.72</td>, <td class="number">171,500</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				3,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-2.00%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">95,700</td>, <td class="number">77,378</td>, <td class="number">132,703</td>, <td class="number">68,420</td>, <td class="number">15,509</td>, <td class="number">2.58</td>, <td class="number">381,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				8,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-2.18%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">105,912</td>, <td class="number">34,275</td>, <td class="number">130,589</td>, <td class="number">158,668</td>, <td class="number">64,660</td>, <td class="number">1.37</td>, <td class="number">273,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				4,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.49%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">63,253</td>, <td class="number">47,375</td>, <td class="number">129,333</td>, <td class="number">682,175</td>, <td class="number">572,093</td>, <td class="number">1.06</td>, <td class="number">31,350</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				350
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.13%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">1,081,249</td>, <td class="number">405,363</td>, <td class="number">127,081</td>, <td class="number">508,893</td>, <td class="number">243,098</td>, <td class="number">0.47</td>, <td class="number">18,050</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				150
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+0.84%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">1,027,967</td>, <td class="number">676,000</td>, <td class="number">122,018</td>, <td class="number">3,106,827</td>, <td class="number">2,901,368</td>, <td class="number">0.60</td>, <td class="number">31,550</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				750
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-2.32%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">5,590,720</td>, <td class="number">357,816</td>, <td class="number">112,891</td>, <td class="number">248,843</td>, <td class="number">114,219</td>, <td class="number">0.87</td>, <td class="number">125,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				3,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+2.46%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">184,950</td>, <td class="number">82,458</td>, <td class="number">103,073</td>, <td class="number">70,884</td>, <td class="number">15,215</td>, <td class="number">3.67</td>, <td class="number">467,000</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				8,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+1.85%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">178,339</td>, <td class="number">21,939</td>, <td class="number">102,455</td>, <td class="number">23,608</td>, <td class="number">4,653</td>, <td class="number">5.26</td>, <td class="number">142,500</td>, <td class="number">
 <img alt="상승" height="6" src="http://imgstock.naver.com/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/><span class="tah p11 red02">
 				5,500
 				</span>
 </td>, <td class="number">
 <span class="tah p11 red01">
 				+4.01%
 				</span>
 </td>, <td class="number">500</td>, <td class="number">1,307,551</td>, <td class="number">67,793</td>, <td class="number">96,605</td>, <td class="number">54,841</td>, <td class="number">17,812</td>, <td class="number">2.81</td>, <td class="number">502,000</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				2,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-0.40%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">31,652</td>, <td class="number">18,870</td>, <td class="number">94,727</td>, <td class="number">64,826</td>, <td class="number">8,199</td>, <td class="number">1.61</td>, <td class="number">146,500</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				2,000
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-1.35%
 				</span>
 </td>, <td class="number">5,000</td>, <td class="number">130,424</td>, <td class="number">56,665</td>, <td class="number">83,015</td>, <td class="number">492,492</td>, <td class="number">313,594</td>, <td class="number">0.61</td>, <td class="number">14,650</td>, <td class="number">
 <img alt="하락" height="6" src="http://imgstock.naver.com/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
 				100
 				</span>
 </td>, <td class="number">
 <span class="tah p11 nv01">
 				-0.68%
 				</span>

In [20]:
all_number_classes = []
for item in piotroski_univ_sets:
    all_number_classes.append(item.string)

In [21]:
all_number_classes

['2,611,000',
 None,
 None,
 '5,000',
 '182,388',
 '129,768',
 '3,388,255',
 '2,621,743',
 '692,113',
 '1.96',
 '80,700',
 None,
 None,
 '5,000',
 '5,250,342',
 '728,002',
 '587,498',
 '322,160',
 '81,925',
 '2.37',
 '2,125,000',
 None,
 None,
 '5,000',
 '27,837',
 '18,419',
 '391,395',
 'N/A',
 'N/A',
 '1.60',
 '142,000',
 None,
 None,
 '5,000',
 '618,302',
 '220,276',
 '312,793',
 '1,788,359',
 '1,064,914',
 '0.57',
 '325,000',
 None,
 None,
 '5,000',
 '176,351',
 '87,187',
 '283,357',
 '797,630',
 '339,246',
 '0.61',
 '388,500',
 None,
 None,
 '5,000',
 '323,605',
 '70,592',
 '274,251',
 '204,871',
 '64,361',
 '2.01',
 '783,000',
 None,
 None,
 '500',
 '86,265',
 '32,963',
 '258,098',
 '63,706',
 '22,410',
 '6.27',
 '134,000',
 None,
 None,
 '100',
 '397,429',
 '189,690',
 '254,185',
 '444,585',
 '233,528',
 '1.21',
 '39,350',
 None,
 None,
 '5,000',
 '2,053,710',
 '641,964',
 '252,613',
 '1,778,370',
 '1,047,865',
 '0.35',
 '51,300',
 None,
 None,
 '5,000',
 '793,866',
 '474,200',
 '243,264',
 '3,956,803',
 '3,639,353',
 '0.78',
 '55,600',
 None,
 None,
 '5,000',
 '969,348',
 '418,112',
 '232,470',
 '3,756,737',
 '3,444,123',
 '0.71',
 '114,500',
 None,
 None,
 '500',
 '200,918',
 '200,000',
 '229,000',
 '2,646,538',
 '2,363,454',
 '0.77',
 '338,000',
 None,
 None,
 '2,500',
 '324,132',
 '66,165',
 '223,638',
 '75,330',
 '34,506',
 '5.48',
 '219,000',
 None,
 None,
 '5,000',
 '301,793',
 '97,344',
 '213,183',
 '417,116',
 '131,536',
 '0.73',
 '245,500',
 None,
 None,
 '500',
 '133,610',
 '80,746',
 '198,231',
 '312,977',
 '151,812',
 '1.09',
 '270,500',
 None,
 None,
 '200',
 '90,304',
 '70,360',
 '190,325',
 '1,030,473',
 '607,206',
 '1.16',
 '191,000',
 None,
 None,
 '5,000',
 '219,277',
 '92,466',
 '176,609',
 '325,813',
 '142,763',
 '1.04',
 '219,000',
 None,
 None,
 '5,000',
 '333,856',
 '68,765',
 '150,594',
 '149,003',
 '39,362',
 '1.38',
 '251,000',
 None,
 None,
 '500',
 '166,797',
 '58,458',
 '146,731',
 '51,816',
 '12,849',
 '4.46',
 '104,500',
 None,
 None,
 '5,000',
 '280,184',
 '137,292',
 '143,471',
 '98,126',
 '26,943',
 '1.87',
 '86,600',
 None,
 None,
 '5,000',
 '1,662,554',
 '163,648',
 '141,719',
 '378,553',
 '244,985',
 '1.30',
 '47,650',
 None,
 None,
 '5,000',
 '627,900',
 '296,003',
 '141,045',
 '3,481,775',
 '3,247,875',
 '0.63',
 '81,400',
 None,
 None,
 '5,000',
 '270,383',
 '172,557',
 '140,462',
 '194,894',
 '52,694',
 '1.03',
 '898,000',
 None,
 None,
 '5,000',
 '22,501',
 '15,618',
 '140,251',
 '45,022',
 '18,813',
 '5.94',
 '120,000',
 None,
 None,
 '2,500',
 '214,217',
 '112,583',
 '135,099',
 '139,590',
 '75,674',
 '2.19',
 '156,500',
 None,
 None,
 '100',
 '255,918',
 '85,018',
 '133,054',
 '19,574',
 '6,471',
 '8.72',
 '171,500',
 None,
 None,
 '500',
 '95,700',
 '77,378',
 '132,703',
 '68,420',
 '15,509',
 '2.58',
 '381,000',
 None,
 None,
 '5,000',
 '105,912',
 '34,275',
 '130,589',
 '158,668',
 '64,660',
 '1.37',
 '273,000',
 None,
 None,
 '500',
 '63,253',
 '47,375',
 '129,333',
 '682,175',
 '572,093',
 '1.06',
 '31,350',
 None,
 None,
 '5,000',
 '1,081,249',
 '405,363',
 '127,081',
 '508,893',
 '243,098',
 '0.47',
 '18,050',
 None,
 None,
 '5,000',
 '1,027,967',
 '676,000',
 '122,018',
 '3,106,827',
 '2,901,368',
 '0.60',
 '31,550',
 None,
 None,
 '5,000',
 '5,590,720',
 '357,816',
 '112,891',
 '248,843',
 '114,219',
 '0.87',
 '125,000',
 None,
 None,
 '500',
 '184,950',
 '82,458',
 '103,073',
 '70,884',
 '15,215',
 '3.67',
 '467,000',
 None,
 None,
 '500',
 '178,339',
 '21,939',
 '102,455',
 '23,608',
 '4,653',
 '5.26',
 '142,500',
 None,
 None,
 '500',
 '1,307,551',
 '67,793',
 '96,605',
 '54,841',
 '17,812',
 '2.81',
 '502,000',
 None,
 None,
 '5,000',
 '31,652',
 '18,870',
 '94,727',
 '64,826',
 '8,199',
 '1.61',
 '146,500',
 None,
 None,
 '5,000',
 '130,424',
 '56,665',
 '83,015',
 '492,492',
 '313,594',
 '0.61',
 '14,650',
 None,
 None,
 '5,000',
 '802,467',
 '559,979',
 '82,037',
 '2,568,514',
 '2,388,040',
 '0.54',
 '109,000',
 None,
 None,
 '5,000',
 '664,072',
 '74,694',
 '81,416',
 '76,626',
 '33,250',
 '1.94',
 '29,100',
 None,
 None,
 '5,000',
 '739,223',
 '261,112',
 '75,984',
 '305,877',
 '177,930',
 '0.62',
 '35,050',
 None,
 None,
 '500',
 '181,762',
 '213,940',
 '74,986',
 '39,790',
 '7,263',
 '2.18',
 '58,700',
 None,
 None,
 '500',
 '230,789',
 '123,875',
 '72,715',
 '96,220',
 '36,605',
 '1.22',
 '96,700',
 None,
 None,
 '500',
 '86,415',
 '74,818',
 '72,349',
 '19,677',
 '7,844',
 '5.99',
 '53,800',
 None,
 None,
 '5,000',
 '435,876',
 '133,446',
 '71,794',
 '323,893',
 '160,256',
 '0.44',
 '440,500',
 None,
 None,
 '5,000',
 '45,258',
 '16,287',
 '71,743',
 'N/A',
 'N/A',
 'N/A',
 '10,600',
 None,
 None,
 '5,000',
 '2,568,540',
 '666,316',
 '70,630',
 '572,678',
 '506,020',
 '0.83',
 '220,500',
 None,
 None,
 '5,000',
 '227,795',
 '31,491',
 '69,437',
 '419,159',
 '246,519',
 '0.40',
 '12,650',
 None,
 None,
 '100',
 '1,421,218',
 '533,800',
 '67,526',
 '38,597',
 '19,748',
 '3.69',
 '37,400',
 None,
 None,
 '5,000',
 '555,155',
 '164,809',
 '61,639',
 '138,179',
 '83,496',
 '1.16',
 '66,100',
 None,
 None,
 '5,000',
 '185,117',
 '92,915',
 '61,417',
 '203,412',
 '114,209',
 '0.90']

In [22]:
# Titles for each number idex
"""1. present_value = 현재가
   2. none
   3. none
   4. face_value = 액면가
   5. quant = 거래량
   6. listed_stock_cnt = 상장주식수
   7. market_sum = 시가총액 
   8. property_total = 자산총액 
   9. debt_total = 부채총액 
   10. pbr = PBR 
   """

# Slicing and creating an individual list for each category 
present_value = all_number_classes[::10]
face_value = all_number_classes[3::10]
quant = all_number_classes[4::10]
listed_stock_cnt = all_number_classes[5::10]
market_sum = all_number_classes[6::10] 
property_total = all_number_classes[7::10]
debt_total = all_number_classes[8::10]
pbr = all_number_classes[9::10]

In [23]:
# Put each category list to DF
df_piotroski['present_value'] = present_value
df_piotroski['quant'] = quant
df_piotroski['property_total'] = property_total
df_piotroski['debt_total'] = debt_total
df_piotroski['listed_stock_cnt'] = listed_stock_cnt
df_piotroski['pbr'] = pbr
df_piotroski['market_sum'] = market_sum
df_piotroski['face_value'] = face_value

In [24]:
df_piotroski

,id,name,market_type,quant,market_sum,property_total,debt_total,listed_stock_cnt,pbr,face_value,present_value
0,005930,삼성전자,1,"182,388","3,388,255","2,621,743","692,113","129,768",1.96,"5,000","2,611,000"
1,000660,SK하이닉스,1,"5,250,342","587,498","322,160","81,925","728,002",2.37,"5,000","80,700"
2,005935,삼성전자우,1,"27,837","391,395",N/A,N/A,"18,419",1.60,"5,000","2,125,000"
3,005380,현대차,1,"618,302","312,793","1,788,359","1,064,914","220,276",0.57,"5,000","142,000"
4,005490,POSCO,1,"176,351","283,357","797,630","339,246","87,187",0.61,"5,000","325,000"
5,051910,LG화학,1,"323,605","274,251","204,871","64,361","70,592",2.01,"5,000","388,500"
6,035420,NAVER,1,"86,265","258,098","63,706","22,410","32,963",6.27,500,"783,000"
7,028260,삼성물산,1,"397,429","254,185","444,585","233,528","189,690",1.21,100,"134,000"
8,015760,한국전력,1,"2,053,710","252,613","1,778,370","1,047,865","641,964",0.35,"5,000","39,350"
9,055550,신한지주,1,"793,866","243,264","3,956,803","3,639,353","474,200",0.78,"5,000","51,300"
10,105560,KB금융,1,"969,348","232,470","3,756,737","3,444,123","418,112",0.71,"5,000","55,600"
11,032830,삼성생명,1,"200,918","229,000","2,646,538","2,363,454","200,000",0.77,500,"114,500"
12,207940,삼성바이오로직스,1,"324,132","223,638","75,330","34,506","66,165",5.48,"2,500","338,000"
13,012330,현대모비스,1,"301,793","213,183","417,116","131,536","97,344",0.73,"5,000","219,000"
14,017670,SK텔레콤,1,"133,610","198,231","312,977","151,812","80,746",1.09,500,"245,500"
15,034730,SK,1,"90,304","190,325","1,030,473","607,206","70,360",1.16,200,"270,500"
16,096770,SK이노베이션,1,"219,277","176,609","325,813","142,763","92,466",1.04,"5,000","191,000"
17,006400,삼성SDI,1,"333,856","150,594","149,003","39,362","68,765",1.38,"5,000","219,000"
18,090430,아모레퍼시픽,1,"166,797","146,731","51,816","12,849","58,458",4.46,500,"251,000"
19,033780,KT&amp;G,1,"280,184","143,471","98,126","26,943","137,292",1.87,"5,000","104,500"
20,066570,LG전자,1,"1,662,554","141,719","378,553","244,985","163,648",1.30,"5,000","86,600"
21,086790,하나금융지주,1,"627,900","141,045","3,481,775","3,247,875","296,003",0.63,"5,000","47,650"
22,003550,LG,1,"270,383","140,462","194,894","52,694","172,557",1.03,"5,000","81,400"
23,051900,LG생활건강,1,"22,501","140,251","45,022","18,813","15,618",5.94,"5,000","898,000"
24,010950,S-Oil,1,"214,217","135,099","139,590","75,674","112,583",2.19,"2,500","120,000"
25,251270,넷마블게임즈,1,"255,918","133,054","19,574","6,471","85,018",8.72,100,"156,500"
26,018260,삼성에스디에스,1,"95,700","132,703","68,420","15,509","77,378",2.58,500,"171,500"
27,011170,롯데케미칼,1,"105,912","130,589","158,668","64,660","34,275",1.37,"5,000","381,000"
28,000810,삼성화재,1,"63,253","129,333","682,175","572,093","47,375",1.06,500,"273,000"
29,000270,기아차,1,"1,081,249","127,081","508,893","243,098","405,363",0.47,"5,000","31,350"
30,000030,우리은행,1,"1,027,967","122,018","3,106,827","2,901,368","676,000",0.60,"5,000","18,050"
31,034220,LG디스플레이,1,"5,590,720","112,891","248,843","114,219","357,816",0.87,"5,000","31,550"
32,002790,아모레G,1,"184,950","103,073","70,884","15,215","82,458",3.67,500,"125,000"
33,036570,엔씨소프트,1,"178,339","102,455","23,608","4,653","21,939",5.26,500,"467,000"
34,035720,카카오,1,"1,307,551","96,605","54,841","17,812","67,793",2.81,500,"142,500"
35,010130,고려아연,1,"31,652","94,727","64,826","8,199","18,870",1.61,"5,000","502,000"
36,009540,현대중공업,1,"130,424","83,015","492,492","313,594","56,665",0.61,"5,000","146,500"
37,024110,기업은행,1,"802,467","82,037","2,568,514","2,388,040","559,979",0.54,"5,000","14,650"
38,009150,삼성전기,1,"664,072","81,416","76,626","33,250","74,694",1.94,"5,000","109,000"
39,030200,KT,1,"739,223","75,984","305,877","177,930","261,112",0.62,"5,000","29,100"
40,035250,강원랜드,1,"181,762","74,986","39,790","7,263","213,940",2.18,500,"35,050"
41,161390,한국타이어,1,"230,789","72,715","96,220","36,605","123,875",1.22,500,"58,700"
42,021240,코웨이,1,"86,415","72,349","19,677","7,844","74,818",5.99,500,"96,700"
43,004020,현대제철,1,"435,876","71,794","323,893","160,256","133,446",0.44,"5,000","53,800"
44,267250,현대로보틱스,1,"45,258","71,743",N/A,N/A,"16,287",N/A,"5,000","440,500"
45,006800,미래에셋대우,1,"2,568,540","70,630","572,678","506,020","666,316",0.83,"5,000","10,600"
46,023530,롯데쇼핑,1,"227,795","69,437","419,159","246,519","31,491",0.40,"5,000","220,500"
47,018880,한온시스템,1,"1,421,218","67,526","38,597","19,748","533,800",3.69,100,"12,650"
48,009830,한화케미칼,1,"555,155","61,639","138,179","83,496","164,809",1.16,"5,000","37,400"
49,078930,GS,1,"185,117","61,417","203,412","114,209","92,915",0.90,"5,000","66,100"

#### ----- BREAK -----

##### Part II : Flipping pages 1 ~ 27

In [25]:
# Looping!

page_num = 1 # KOSPI 27 pages

stock_id_ls = []
stock_name_ls = [] 

all_number_classes = [] 

for num in range(1, page_num + 28): 
    url_p = "http://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn%3Fsosok%3D{0}%26page%3D{1}&fieldIds={2}&fieldIds={3}&fieldIds={4}&fieldIds={5}&fieldIds={6}&fieldIds={7}".format('0',
                                                                                                                                                                                                                                                                   num, 
                                                                                                                                                                                                                                                                   'quant',
                                                                                                                                                                                                                                                                   'listed_stock_cnt',
                                                                                                                                                                                                                                                                   'market_sum',
                                                                                                                                                                                                                                                                   'property_total',
                                                                                                                                                                                                                                                                   'debt_total',
                                                                                                                                                                                                                                                                   'pbr')
    
    r = requests.get(url_p)
    html = r.text 
    
    soup = BeautifulSoup(html, 'lxml')
    
    stock_ids = soup.select('a[href*="/item/main.nhn"]')
    piotroski_univ_sets = soup.select('td[class^="number"]')
    
    # Looping stock ids and names 
    for id in stock_ids: 
        stock_id_ls.append(str(id).strip('"<>/a').split('=')[-1].split('">')[0])
        stock_name_ls.append(str(id).strip('"<>/a').split('=')[-1].split('">')[1])
        
    # Looping Number Classes for each stock    a
    for item in piotroski_univ_sets: 
        all_number_classes.append(item.string)

In [29]:
# Convert stock ids & names lists to Pandas DF 
df_piotroski = pd.DataFrame({'id' : stock_id_ls, 'name': stock_name_ls, 'market_type': 1}, columns = ['id', 'name','market_type', 'quant', 'market_sum', 'property_total', 'debt_total', 'listed_stock_cnt', 'pbr', 'face_value',])

# Slicing and creating an individual list for each category 
present_value = all_number_classes[::10]
face_value = all_number_classes[3::10]
quant = all_number_classes[4::10]
listed_stock_cnt = all_number_classes[5::10]
market_sum = all_number_classes[6::10] 
property_total = all_number_classes[7::10]
debt_total = all_number_classes[8::10]
pbr = all_number_classes[9::10] 

# Put each category list to DF
df_piotroski['present_value'] = present_value
df_piotroski['quant'] = quant
df_piotroski['property_total'] = property_total
df_piotroski['debt_total'] = debt_total
df_piotroski['listed_stock_cnt'] = listed_stock_cnt
df_piotroski['pbr'] = pbr
df_piotroski['market_sum'] = market_sum
df_piotroski['face_value'] = face_value

In [30]:
df_piotroski

,id,name,market_type,quant,market_sum,property_total,debt_total,listed_stock_cnt,pbr,face_value,present_value
0,005930,삼성전자,1,"182,388","3,388,255","2,621,743","692,113","129,768",1.96,"5,000","2,611,000"
1,000660,SK하이닉스,1,"5,250,342","587,498","322,160","81,925","728,002",2.37,"5,000","80,700"
2,005935,삼성전자우,1,"27,837","391,395",N/A,N/A,"18,419",1.60,"5,000","2,125,000"
3,005380,현대차,1,"618,302","312,793","1,788,359","1,064,914","220,276",0.57,"5,000","142,000"
4,005490,POSCO,1,"176,351","283,357","797,630","339,246","87,187",0.61,"5,000","325,000"
5,051910,LG화학,1,"323,605","274,251","204,871","64,361","70,592",2.01,"5,000","388,500"
6,035420,NAVER,1,"86,265","258,098","63,706","22,410","32,963",6.27,500,"783,000"
7,028260,삼성물산,1,"397,429","254,185","444,585","233,528","189,690",1.21,100,"134,000"
8,015760,한국전력,1,"2,053,710","252,613","1,778,370","1,047,865","641,964",0.35,"5,000","39,350"
9,055550,신한지주,1,"793,866","243,264","3,956,803","3,639,353","474,200",0.78,"5,000","51,300"
10,105560,KB금융,1,"969,348","232,470","3,756,737","3,444,123","418,112",0.71,"5,000","55,600"
11,032830,삼성생명,1,"200,918","229,000","2,646,538","2,363,454","200,000",0.77,500,"114,500"
12,207940,삼성바이오로직스,1,"324,132","223,638","75,330","34,506","66,165",5.48,"2,500","338,000"
13,012330,현대모비스,1,"301,793","213,183","417,116","131,536","97,344",0.73,"5,000","219,000"
14,017670,SK텔레콤,1,"133,610","198,231","312,977","151,812","80,746",1.09,500,"245,500"
15,034730,SK,1,"90,304","190,325","1,030,473","607,206","70,360",1.16,200,"270,500"
16,096770,SK이노베이션,1,"219,277","176,609","325,813","142,763","92,466",1.04,"5,000","191,000"
17,006400,삼성SDI,1,"333,856","150,594","149,003","39,362","68,765",1.38,"5,000","219,000"
18,090430,아모레퍼시픽,1,"166,797","146,731","51,816","12,849","58,458",4.46,500,"251,000"
19,033780,KT&amp;G,1,"280,184","143,471","98,126","26,943","137,292",1.87,"5,000","104,500"
20,066570,LG전자,1,"1,662,554","141,719","378,553","244,985","163,648",1.30,"5,000","86,600"
21,086790,하나금융지주,1,"627,900","141,045","3,481,775","3,247,875","296,003",0.63,"5,000","47,650"
22,003550,LG,1,"270,383","140,462","194,894","52,694","172,557",1.03,"5,000","81,400"
23,051900,LG생활건강,1,"22,501","140,251","45,022","18,813","15,618",5.94,"5,000","898,000"
24,010950,S-Oil,1,"214,217","135,099","139,590","75,674","112,583",2.19,"2,500","120,000"
25,251270,넷마블게임즈,1,"255,918","133,054","19,574","6,471","85,018",8.72,100,"156,500"
26,018260,삼성에스디에스,1,"95,700","132,703","68,420","15,509","77,378",2.58,500,"171,500"
27,011170,롯데케미칼,1,"105,912","130,589","158,668","64,660","34,275",1.37,"5,000","381,000"
28,000810,삼성화재,1,"63,253","129,333","682,175","572,093","47,375",1.06,500,"273,000"
29,000270,기아차,1,"1,081,249","127,081","508,893","243,098","405,363",0.47,"5,000","31,350"
...,...,...,...,...,...,...,...,...,...,...,...
1325,090355,노루페인트우,1,"3,855",43,N/A,N/A,463,0.70,500,"9,390"
1326,001065,JW중외제약우,1,"3,703",43,N/A,N/A,161,2.06,"2,500","26,950"
1327,000995,동부하이텍1우,1,30,43,N/A,N/A,112,4.88,"5,000","38,550"
1328,004835,덕성우,1,"3,399",43,N/A,N/A,"1,392",0.73,500,"3,110"
1329,005965,동부건설우,1,"1,447",43,N/A,N/A,226,1.59,"5,000","19,100"
1330,014285,금강공업우,1,452,43,N/A,N/A,118,0.63,"5,000","36,350"
1331,227560,TIGER 200 생활소비재,1,"1,394",42,N/A,N/A,340,N/A,0,"12,245"
1332,001527,동양2우B,1,"1,237",41,N/A,N/A,309,3.28,500,"13,400"
1333,004985,성신양회우,1,"2,084",40,N/A,N/A,736,0.43,"5,000","5,440"
1334,161500,ARIRANG 경기주도주,1,245,40,N/A,N/A,600,N/A,0,"6,590"
1335,016385,동부제철우,1,"1,044",40,N/A,N/A,160,4.98,"5,000","24,650"
1336,000325,노루홀딩스우,1,75,39,N/A,N/A,185,0.64,500,"21,300"
1337,227550,TIGER 200 산업재,1,405,39,N/A,N/A,660,N/A,0,"5,920"
1338,001067,JW중외제약2우B,1,"7,101",39,N/A,N/A,84,3.50,"2,500","45,900"
1339,000227,유유제약2우B,1,"161,395",38,N/A,N/A,164,2.10,"1,000","23,150"
1340,002785,진흥기업우B,1,"3,386",37,N/A,N/A,857,-35.76,500,"4,365"
1341,253160,ARIRANG 200선물인버스2X,1,"1,244",37,N/A,N/A,300,N/A,0,"12,335"
1342,000547,흥국화재2우B,1,"5,782",35,N/A,N/A,154,2.73,"5,000","23,100"
1343,140580,KBSTAR 우량업종,1,"1,231",35,N/A,N/A,300,N/A,0,"11,580"
1344,139310,TIGER 금속선물(H),1,375,34,N/A,N/A,600,N/A,0,"5,750"
1345,157510,TIGER 자동차,1,"1,488",34,N/A,N/A,260,N/A,0,"13,115"
1346,001799,대한제당3우B,1,209,33,N/A,N/A,130,0.51,"2,500","25,400"
1347,013367,일성건설2우B,1,"10,075",31,N/A,N/A,621,2.78,500,"5,020"
1348,008355,남선알미우,1,"3,785",28,N/A,N/A,308,8.34,500,"9,250"
1349,002787,진흥기업2우B,1,"3,569",28,N/A,N/A,295,-77.58,500,"9,470"
1350,004989,성신양회3우B,1,44,24,N/A,N/A,287,0.66,"5,000","8,380"
1351,001529,동양3우B,1,"1,965",23,N/A,N/A,90,6.31,500,"25,800"
1352,161490,ARIRANG 경기방어주,1,"1,013",23,N/A,N/A,300,N/A,0,"7,570"
1353,004987,성신양회2우B,1,"7,207",22,N/A,N/A,221,0.79,"5,000","10,150"
1354,000327,노루홀딩스2우B,1,0,18,N/A,N/A,93,0.58,500,"19,600"

In [31]:
stocks = df_piotroski[['id', 'name', 'market_type']]

In [44]:
stocks = stocks.rename(columns = {'id' : 'stock_code', 'name' : 'company'})

In [51]:
stocks.head()

  stock_code company  market_type
0     005930    삼성전자            1
1     000660  SK하이닉스            1
2     005935   삼성전자우            1
3     005380     현대차            1
4     005490   POSCO            1

#### ------ BREAK -----

##### Part III. Put the DF to PostgreSQL

In [32]:
# Importing relavent packages from sqlalchemy ORM
from datetime import datetime

from sqlalchemy import create_engine
from sqlalchemy import Table, Column, Integer, String, DateTime, ForeignKey
from sqlalchemy.orm import relationship, backref, sessionmaker
from sqlalchemy.ext.declarative import declarative_base

In [33]:
db_string = "postgresql://daesik:@localhost/db_piotroski"

engine = create_engine(db_string, echo=True)

In [34]:
Session = sessionmaker(bind=engine)
session = Session()

In [35]:
Base = declarative_base()

In [36]:
class Stock(Base):
    __tablename__ = 'stocks'
    
    stock_id = Column(Integer, primary_key=True)
    stock_code = Column(String, unique=True, nullable=False)
    company = Column(String, index=True, unique=True, nullable=False)
    market_type = Column(Integer)
    industry = Column(String)
    created_on = Column(DateTime, default=datetime.utcnow)
    updated_on = Column(DateTime, default=datetime.utcnow)
    
    # one-to-many & many-to-one relationship setting, if needed
    base_param = relationship("BaseParam", back_populates="stocks")
    bookmarket_param = relationship("BookMarketParam", back_populates="stocks")
    
    def __repr__(self): 
        return "<Stock --> id : {0}, code : {1}, company : {2}, market_type : {3}, created : {4}, updated : {5}>".format(self.stock_id, 
                                                                                                                         self.stock_code, 
                                                                                                                         self.company, 
                                                                                                                         self.market_type, 
                                                                                                                         self.created_on, 
                                                                                                                         self.updated_on,)

In [37]:
class BaseParam(Base): 
    __tablename__= 'base_params'
    
    baseparam_id = Column(Integer, primary_key=True)
    stock_code = Column(String, ForeignKey('stocks.stock_code'))
    date = Column(DateTime)
    price_open = Column(Integer)
    price_close = Column(Integer)
    price_high = Column(Integer)
    price_low = Column(Integer)
    quant = Column(Integer)
    market_sum = Column(Integer)
    
    # one-to-many relationship setting
    stock = relationship("Stock", back_populates="base_params")
    
    # 거래량, 향후 volume으로 변경가능. 네이버 파라미터와 맞추기 위해 quant 사용

In [38]:
class BookMarketParam(Base):
    __tablename__= 'bookmarket_params'
    
    bookmarketparam_id = Column(Integer, primary_key=True)
    stock_code = Column(String, ForeignKey('stocks.stock_code'))
    listed_stock_cnt = Column(Integer)
    property_total = Column(Integer)
    debt_total = Column(Integer)
    pbr = Column(Integer)
    
    # one-to-many relationship setting
    stock = relationship('Stock', back_populates='bookmarket_params')
    
    
    # 회사이름 및 분기 컬럼 추가??? 재무제표 관련 자료

In [39]:
Base.metadata.create_all(engine)

2017-09-20 23:51:07,356 INFO sqlalchemy.engine.base.Engine select version()
2017-09-20 23:51:07,357 INFO sqlalchemy.engine.base.Engine {}
2017-09-20 23:51:07,361 INFO sqlalchemy.engine.base.Engine select current_schema()
2017-09-20 23:51:07,362 INFO sqlalchemy.engine.base.Engine {}
2017-09-20 23:51:07,364 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2017-09-20 23:51:07,366 INFO sqlalchemy.engine.base.Engine {}
2017-09-20 23:51:07,369 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2017-09-20 23:51:07,371 INFO sqlalchemy.engine.base.Engine {}
2017-09-20 23:51:07,372 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2017-09-20 23:51:07,374 INFO sqlalchemy.engine.base.Engine {}
2017-09-20 23:51:07,378 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2017-09-20 23:51:07,379 INFO sqlalchemy.engine.base.Engine {'name': 'stocks'}
2017-09-20 23:51:07,383 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2017-09-20 23:51:07,385 INFO sqlalchemy.engine.base.Engine {'name': 'base_params'}
2017-09-20 23:51:07,388 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2017-09-20 23:51:07,389 INFO sqlalchemy.engine.base.Engine {'name': 'bookmarket_params'}

In [46]:
# send data to PostgreSQL 
stocks.to_sql('stocks', engine, index = False, if_exists = 'append')

2017-09-21 00:02:44,929 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2017-09-21 00:02:44,931 INFO sqlalchemy.engine.base.Engine {'name': 'stocks'}
2017-09-21 00:02:44,935 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2017-09-21 00:02:44,947 INFO sqlalchemy.engine.base.Engine INSERT INTO stocks (stock_code, company, market_type) VALUES (%(stock_code)s, %(company)s, %(market_type)s)
2017-09-21 00:02:44,950 INFO sqlalchemy.engine.base.Engine ({'stock_code': '005930', 'company': '삼성전자', 'market_type': 1}, {'stock_code': '000660', 'company': 'SK하이닉스', 'market_type': 1}, {'stock_code': '005935', 'company': '삼성전자우', 'market_type': 1}, {'stock_code': '005380', 'company': '현대차', 'market_type': 1}, {'stock_code': '005490', 'company': 'POSCO', 'market_type': 1}, {'stock_code': '051910', 'company': 'LG화학', 'market_type': 1}, {'stock_code': '035420', 'company': 'NAVER', 'market_type': 1}, {'stock_code': '028260', 'company': '삼성물산', 'market_type': 1}  ... displaying 10 of 1355 total bound parameter sets ...  {'stock_code': '004987', 'company': '성신양회2우B', 'market_type': 1}, {'stock_code': '000327', 'company': '노루홀딩스2우B', 'market_type': 1})
2017-09-21 00:02:45,355 INFO sqlalchemy.engine.base.Engine COMMIT